### ISSUE TITLE
Rules not working

### ISSUE THREAD

**Issue by adrianguanipa** [jorenn92/Maintainerr#1009]
Hey there,

Could I get some help here, I have a test rule configured for movies added after March 25th, and when testing my media against that rule they are coming back as "true" but when running the rule manually nothing is happening, I don't see the movies being added to the collection, what am I missing here?

![image](https://github.com/jorenn92/Maintainerr/assets/64798434/9e4ad5d2-93fd-499f-8bf7-13a49092d924)

![image](https://github.com/jorenn92/Maintainerr/assets/64798434/5fbb458e-e570-4abd-b507-d926cb43ecd5)

Thanks.

**Comment by adrianguanipa** [comment]
> Hey!
> 
> Are you certain the ‘rule handler’ execution is finished? It might take a while on big libraries.

I only have two movies in this Plex instance, as I want to see it in action first :), I also left it running overnight and still shows this way.

**Comment by jorenn92** [comment]
Can you share logs? It should log the execution of your rules. Perhaps they encountered an error.

**Comment by adrianguanipa** [comment]
Good idea, I see it complaining about applications not being reachable, I don't have it connected to Radarr but just Plex, the rule is only set to delete not to unmonitor the files, does this means having Radarr or Sonarr connect is a requirement?

2024/03/27 14:51:13
stdout
[maintainerr] | 27/03/2024 18:51:13  [INFO] [RuleExecutorService] Not all applications are reachable.. Skipped rule execution.
2024/03/27 14:51:03
stdout
[maintainerr] | 27/03/2024 18:51:03  [INFO] [RuleExecutorService] Starting Execution of all active rules

**Comment by jorenn92** [comment]
You can attempt to connect other apps and observe if it behaves differently. I don't have access to the code currently, so i can’t verify if it's necessary. But it shouldn't be required.

**Comment by adrianguanipa** [comment]
Will do, thank you.

**Comment by adrianguanipa** [comment]
That was the problem, I've added Radarr and Sonarr and now I see it working, so it does seem like those are a requirement.

Thank you

**Comment by jorenn92** [comment]
> That was the problem, I've added Radarr and Sonarr and now I see it working, so it does seem like those are a requirement.
> 
> Thank you

No problem, I'll investigate why they're necessary later. They shouldn't be mandatory.
