### ISSUE TITLE
Will not connect to Radarr or Sonarr 

### ISSUE THREAD

**Issue by leftie2** [jorenn92/Maintainerr#1038]
Maintainerr installed via Docker, as described in the docs.
Radarr, and Sonarr installed on the same machine, and are all listening via plain and SSL ports on the interface IP address.

With the fresh Maintainerr install, no matter what combination of http(s)://<domain/ip> <port> I attempted to enter into the Settings pages, Maintainer would not connect to Radarr, or Sonarr. Plex connected right away after authenticating.

OS: Debian 12.5
Docker: 20.10.24

The only error message is:

Connection failed! Please check and save your settings

Only entry I see in the log file in the data folder is:
[maintainerr]  |  23/03/2024 00:53:28  [WARN] [RadarrApi] Couldn't fetch Radarr info.. Is Radarr up?

**Comment by jorenn92** [comment]
In the past, such issues often stemmed from misconfiguring the 'base URL' property, which should be empty if not configured in Radarr/Sonarr. If this isn't the issue, consider intercepting the network request to the backend when saving. You can use your browser's dev tools, specifically the network tab, to do this. It's possible a bug is affecting your URL.

**Comment by leftie2** [comment]
I was clicking "Test" before "Saving".

An improvement might be to grey out the Test button until you Save as Test doesn't seem to work until you save :)
