### ISSUE TITLE
Respect hostname/IP address settings

### ISSUE THREAD

**Issue by eyeruleall** [jorenn92/Maintainerr#1060]
**Describe the bug**
The app does not respect hostname settings. When using hostnames for radarr/sonarr, the app fails to respect that setting and connects using IP addresses. This causes an issue if the IP address ever changes.

**To Reproduce**
1. Go to 'settings' and setup radarr with a DNS hostname, something like "http://radarr/".
2. Restart or remove and recreate radarr container so the IP address changes.
3. Debug Logs show connection failure, trying to connect using an IP address and not a hostname. "[DEBUG] [RadarrApi] connect ECONNREFUSED 172.19.0.2:7878"

**Expected behavior**
Instead of "172.19.0.2:7878" it should be trying to connect on "http://radarr:7878/" because the app is setup using a hostname, and not an IP address. 

If a user enters a hostname in setup, the app should connect using that hostname. If the user enters an ip address, the app should connect using that IP address.

**Device (please complete the following information):**
 - OS: Docker
 - Version: 26.1.0, build 9714adc

**Comment by eyeruleall** [comment]
Okay maybe it was just me and Radarr was down. Close if the app is looking up the IP address as necessary.

**Comment by jorenn92** [comment]
I don't believe this issue lies with the Maintainer. The application doesn't directly retrieve the IP address; rather, it utilizes the configuration within its API calls. My suspicion is that the IP address in question originated from Docker's DNS resolution.

**Comment by eyeruleall** [comment]
I'm closing this as I think this was an issue on my end.
