### ISSUE TITLE
Overseerr - Media downloaded date is 1970-01-01

### ISSUE THREAD

**Issue by gebs** [jorenn92/Maintainerr#1113]
**Describe the bug**
A few movies get added to the collections to early. Testing the media reveals that the Overseerr - Media downloaded date is set to 1970-01-01. In Overseerr I'm not able to find this date. So i'm not sure if it's a configuration issue.

**Expected behavior**
The field Overseerr - Media downloaded date should have the correct date the movie was downloaded.

**Screenshots**
![image](https://github.com/jorenn92/Maintainerr/assets/14344456/e3e1bcd0-d057-482e-a235-125ca93595b7)

**Comment by gebs** [comment]
Had a further look at it. My Overseerr => Plex connection was broken, so it didn't report a downloaded date (returned null). Solved after reconfiguring Plex in Overseerr

I figure the date is not nullable and falls back to the first date.  I think it would be good to not include items without downloaded date in the collection, better to delete too little than too much.

**Comment by jorenn92** [comment]
Ah, good catch. It's a good idea to filter items with this 1970 date out of the selection,

**Comment by Gwindalmir** [comment]
I noticed this with radarr too if it looks up a movie that was never requested in there (i.e. manually added to Plex).
I had to make sure I also checked for "is monitored", or my checks for older than 60 days would have false positives.

```yaml
ruleResults:
        - operator: OR
          action: before
          firstValueName: Radarr - Date added
          firstValue: 0001-01-01T07:53:00.000Z
          secondValueName: custom_days
          secondValue: 2024-05-09T08:26:46.983Z
          result: true
        - operator: AND
          action: equals
          firstValueName: Radarr - is monitored
          firstValue: null
          secondValueName: boolean
          secondValue: 1
          result: false```
