### ISSUE TITLE
'Requested in Overseer' and 'Overseer request by user' not working

### ISSUE THREAD

**Issue by moust4ki** [jorenn92/Maintainerr#1188]
Maybe linked to https://github.com/jorenn92/Maintainerr/issues/1168

**Describe the bug**
If I select the filter "Requested in Overseer", it will always return FALSE even if I can see the media and the requester in Overseer. 
Also the "Overseer - Requested by user" fail to work: If I make a filter with any user as requester its always treated as false

(Probably duplicate of :  )

**To Reproduce**
![CleanShot 2024-07-29 at 15 29 01@2x](https://github.com/user-attachments/assets/b64c5128-6632-40d1-91e6-8b3fa0e393a9)
![CleanShot 2024-07-29 at 15 25 29@2x](https://github.com/user-attachments/assets/374b45ab-8ee4-4ef6-af8f-af3bb26030f0)
![CleanShot 2024-07-29 at 15 29 43@2x](https://github.com/user-attachments/assets/b870d876-d2d2-4ccc-8c2b-a6b6658c6dc9)

AND
![CleanShot 2024-07-29 at 15 31 10@2x](https://github.com/user-attachments/assets/2de975ad-4423-460f-a8d2-f968ae4c8ad7)
![CleanShot 2024-07-29 at 15 26 24@2x](https://github.com/user-attachments/assets/0ccbbb9e-1638-45ba-a563-9eb83114d63b)
![CleanShot 2024-07-29 at 15 32 03@2x](https://github.com/user-attachments/assets/c10c16a5-51a9-4d82-909c-801827ee4509)

**Device (please complete the following information):**
 - OS: Unraid + Docker
 - Version 6.12.6

**Comment by davidebonavita** [comment]
Same issue here with version 2.0.4 pulled from https://registry.hub.docker.com/r/jorenn92/maintainerr/

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/9484b225-e53d-49b3-9e64-66e02a925f84">

**Comment by jorenn92** [comment]
Hey! 

Is there anything in the log file when you perform the test? Preferably with debug' enabled.

**Comment by jorenn92** [comment]
There was a mismatch when a Plex user used a 'display name'. I don't know when this changed, since it used to work with display names, but this should be handled in PR https://github.com/jorenn92/Maintainerr/pull/1231. If anyone could try it out with the main/develop image, that would be a great help!

**Comment by davidebonavita** [comment]
> There was a mismatch when a Plex user used a 'display name'. I don't know when this changed, since it used to work with display names, but this should be handled in PR #1231. If anyone could try it out with the main/develop image, that would be a great help!

Good news, it seems to be fixed on the develop image, thanks!
<img width="674" alt="image" src="https://github.com/user-attachments/assets/e635aac5-7b3a-424c-9a55-86f51f8e3f85">

![image](https://github.com/user-attachments/assets/ec6f9772-0146-4375-a487-84f6d06c11d2)

**Comment by imrman** [comment]
on develop and still can't see overseer user details:
![image](https://github.com/user-attachments/assets/96a9090b-434d-4dac-8c28-47dee15b1f67)
![image](https://github.com/user-attachments/assets/a7b7d35a-38c2-42bc-ac1c-b191f93a14dc)

**Comment by jorenn92** [comment]
> on develop and still can't see overseer user details: ![image](https://private-user-images.githubusercontent.com/5221352/376009095-96a9090b-434d-4dac-8c28-47dee15b1f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODcxMzksIm5iZiI6MTcyODg4NjgzOSwicGF0aCI6Ii81MjIxMzUyLzM3NjAwOTA5NS05NmE5MDkwYi00MzRkLTRkYWMtOGMyOC00N2RlZTE1YjFmNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMDYyMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZmMjU0MDU2NWViOWVlMGViYzg4NWQ1MjU4ZGUzNWQ1YTg2YTJjY2IxZjBiY2ZkNmE3YjVkZTk4YzhhMzZkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lDlH2W70P_rBQ4M_Ezz62i_6PQ5eYfe7bVVNCP8C34M) ![image](https://private-user-images.githubusercontent.com/5221352/376009100-a7b7d35a-38c2-42bc-ac1c-b191f93a14dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODcxMzksIm5iZiI6MTcyODg4NjgzOSwicGF0aCI6Ii81MjIxMzUyLzM3NjAwOTEwMC1hN2I3ZDM1YS0zOGMyLTQyYmMtYWMxYy1iMTkxZjkzYTE0ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMDYyMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA2MmZiOWUyMDQzOWIxYTlmYmRjZTVjMDliNGZhOWY0NzA1M2M5YWFjYWY0ZmVkZGEwMTNjZDQ0ZmY4ZWExMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.65N9wmmOZkz6oZ7KieMpQwNzIDhdmHCGnFHQ0mFaSNw)

Could you share some more info about the user? Is it a Plex user or a local Overseerr user? Is there something special about the user? Like a different display name than the account name. What's your Plex version?

Do you have Maintainerr / Overseerr logs (preferably debug)?

**Comment by imrman** [comment]
@jorenn92 I've regeenrated all the API keys and working now, it was probably an API key issue (altough it was nice if the maintainerr logs showed that...
wierd thing though: when i wrote the comment, when i did "Test saved" it showed no error.

**Comment by benscobie** [comment]
Closing this as it appears to be resolved. Please raise a new issue if you come across it again.
