### ISSUE TITLE
Fresh install with Docker Compose: UI doesn't load

### ISSUE THREAD

**Issue by chrisbenincasa** [jorenn92/Maintainerr#1195]
**Describe the bug**
All pages fail to load - no UI appears, spinner spins indefinitely, and there are errors in the console and container logs

**To Reproduce**
1. Create container with the docker compose installation from the README
2. Go to IP:6246
3. See loading spinner that spins indefinitely on all pages

**Expected behavior**
UI loads

**Screenshots**
<img width="675" alt="Screenshot 2024-07-30 at 10 42 36 PM" src="https://github.com/user-attachments/assets/35c49f62-3278-4841-a6ec-c17e363c431e">

**Device (please complete the following information):**
 - OS: Accessing from macOS on Chrome; using the amd64 container image
 - Version: latest (2.0.4)

**Additional context**
Logs from container:
```
Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',

  port: 3001
}
```

Assuming there is some component that spins up on this port within the container that is failing, but I see no other logs related to that.

My compose:
```docker-compose.yml
version: '3'

services:
    maintainerr:
        image: ghcr.io/jorenn92/maintainerr:latest # or jorenn92/maintainerr:latest
        container_name: maintainerr
        user: 1002:1002   # the "maintainerr" user and group on my system
        volumes:
          - type: bind
            source: /data/maintainerr
            target: /opt/data
        environment:
          - TZ=America/New_York
        ports:
          - 6246:6246
        restart: unless-stopped
```

**Comment by dhayab** [comment]
I had the same issue and was about to stop the container when I got interrupted by something. When I came back the app was properly bootstrapped. It took ~3 minutes in my case:

```
2024-07-31T21:48:27.285972200Z   ▲ Next.js 14.2.3
2024-07-31T21:48:27.286535641Z   - Local:        http://localhost:6246
2024-07-31T21:48:27.286608605Z   - Network:      http://0.0.0.0:6246
2024-07-31T21:48:27.287591909Z 
2024-07-31T21:48:27.288059993Z  ✓ Starting...
2024-07-31T21:48:44.775227542Z  ✓ Ready in 17.5s

[...]

2024-07-31T21:51:30.076940197Z [maintainerr] | 31/07/2024 23:51:30  [INFO] [NestApplication] Nest application successfully started
```

**Comment by jorenn92** [comment]
Could you share your full log file? Preferably with the DEBUG=true env var enabled. It seems like the backend wasn't started successfully and/or crashed completely.

**Comment by chrisbenincasa** [comment]
Definitely. Will post as soon as I can

**Comment by chrisbenincasa** [comment]
Think this is resolved now, actually. I think it may have been the same issue that @dhayab mentioned. Sorry for the noise!
