### ISSUE TITLE
Unable to connect to Sonarr 4.0.9.2244 or Radarr 5.9.1.9070

### ISSUE THREAD

**Issue by Natejt** [jorenn92/Maintainerr#1256]
**Describe the bug**
New installation, entering IP address, port, and API key for Radarr or Sonarr fails test every time.  Maintainerr logs state:
`[WARN] [SonarrApi] Couldn't fetch Sonarr info.. Is Sonarr up?
[WARN] [RadarrApi] Couldn't fetch Radarr info.. Is Radarr up?`

No logs found in Radarr, but Sonarr has both `Sonarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.` and `LanguageProfileController|API call made to deprecated endpoint from axios/1.3.4`

Both Radarr and Sonarr are set to Authentication and Certificate Validation disabled for Local Addresses

**To Reproduce**
1. Enter connection details for Radarr or Sonarr
2. Click on Test Saved
3. See 'Connection failed! Please check and save your settings'

**Expected behavior**
Connection test expected to be successful.

**Device (please complete the following information):**
 - OS: Docker
 - Version 2.1.0

**Additional context**
Unable to test collection generation without sonarr or radarr because once details are entered, they cannot be removed without seeing 'Not all fields contain values'

**Comment by ydkmlt84** [comment]
Try saving changes first before you test SAVED.

**Comment by ydkmlt84** [comment]
For future reference the issue was a networking problem. Ensuring all containers involved were on the same docker network, then using the containers' hostname in Maintainerr settings. All is connected successfully.

**Comment by jorenn92** [comment]
@ydkmlt84, Am I correct in understanding that the issue has been resolved? Can we close it? & Thanks for helping him out!

**Comment by ydkmlt84** [comment]
Yes it can be closed. Worked it out on discord.
