### ISSUE TITLE
Radarr - [list] Tags (Text if 1, otherwise list) turns out empty

### ISSUE THREAD

**Issue by xl3laz3rx** [jorenn92/Maintainerr#1276]
The Radarr [list] tag turns out to be empty, is use within radarr tags for every movie

<img width="756" alt="Scherm­afbeelding 2024-09-18 om 07 40 19" src="https://github.com/user-attachments/assets/d6b4fe8f-fb5a-4d35-9367-78926ef2aff5">

<img width="461" alt="Scherm­afbeelding 2024-09-18 om 07 40 35" src="https://github.com/user-attachments/assets/981d0775-8dea-4237-aa28-e27c19a92d00">

The same issue is also with Sonarr.

**Device (please complete the following information):**
 - OS: Ubuntu 24.04
 - Version 2.1.2

**Comment by jorenn92** [comment]
Hey! 
Is there anything related in the logs?
What versions of Radarr & Sonarr are you using? 
This still works on my end with Radarr 5.9.1.9070 & Sonarr 4.0.9.2244

**Comment by xl3laz3rx** [comment]
Hi Jorenn, 

I made a mistake. I migrated my vm's and switched sonarrr with radarr (some how maintainerr said connection success).
All fixed now.
