### ISSUE TITLE
Community rules unreachable

### ISSUE THREAD

**Issue by chriscarpenter12** [jorenn92/Maintainerr#1278]
**Describe the bug**
First time setting this up and I was attempting to click the Community rules button to get an idea of how they work, but it just spins. Looks like the [url in the code](https://github.com/jorenn92/Maintainerr/blob/main/server/src/modules/rules/rules.service.ts#L43) is not loading for me.

**To Reproduce**
1. Add a rule
2. Click on 'Community' rules

**Expected behavior**
Shows a list of rules?

**Screenshots**
![Screenshot 2024-09-19 at 3 58 27 PM](https://github.com/user-attachments/assets/7c14b840-c53a-43ea-8c56-237469836830)

**Device (please complete the following information):**
 - OS: Debian 12
 - Version: ghcr.io/jorenn92/maintainerr:latest

**Comment by Serph91P** [comment]
> **Describe the bug** First time setting this up and I was attempting to click the Community rules button to get an idea of how they work, but it just spins. Looks like the [url in the code](https://github.com/jorenn92/Maintainerr/blob/main/server/src/modules/rules/rules.service.ts#L43) is not loading for me.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Add a rule
> 
>     2. Click on 'Community' rules
> 
> 
> **Expected behavior** Shows a list of rules?
> 
> **Screenshots** ![Screenshot 2024-09-19 at 3 58 27 PM](https://private-user-images.githubusercontent.com/458486/369150763-7c14b840-c53a-43ea-8c56-237469836830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjA3MTQsIm5iZiI6MTcyNjg2MDQxNCwicGF0aCI6Ii80NTg0ODYvMzY5MTUwNzYzLTdjMTRiODQwLWM1M2EtNDNlYS04YzU2LTIzNzQ2OTgzNjgzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxOTI2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzgyZGZjMmQ0NmM5YzBkZjZjZTczMGQ2OTJiZGIzZjI3ZDgxZTYyMjNiNjkyYWVkMzU5Njc4YzZlY2ZhYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.80WsmyDI7FTfyCX2cA7m4lZDd8kD2fz50Tk4veL6qN8)
> 
> **Device (please complete the following information):**
> 
>     * OS: Debian 12
> 
>     * Version: ghcr.io/jorenn92/maintainerr:latest

seems to work again

**Comment by chriscarpenter12** [comment]
The community rules url in the code doesn't though. 

```
~ > curl -v -H "token 788bfded-1fd0-46e8-8616-28d76e8a2904" https://jsonbin.maintainerr.info/maintainerr-app/rules
* Host jsonbin.maintainerr.info:443 was resolved.
* IPv6: 2606:4700:3037::6815:2804, 2606:4700:3034::ac43:acd9
* IPv4: 172.67.172.217, 104.21.40.4
*   Trying 172.67.172.217:443...
* Connected to jsonbin.maintainerr.info (172.67.172.217) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=maintainerr.info
*  start date: Jul 25 21:08:35 2024 GMT
*  expire date: Oct 23 21:08:34 2024 GMT
*  subjectAltName: host "jsonbin.maintainerr.info" matched cert's "*.maintainerr.info"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://jsonbin.maintainerr.info/maintainerr-app/rules
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: jsonbin.maintainerr.info]
* [HTTP/2] [1] [:path: /maintainerr-app/rules]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET /maintainerr-app/rules HTTP/2
> Host: jsonbin.maintainerr.info
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/2 500
< date: Fri, 20 Sep 2024 19:30:25 GMT
< content-type: application/json; charset=utf-8
< content-length: 74
< access-control-allow-origin: *
< etag: W/"4a-MkwWBrMgISwgXsHeCTALVUl4eao"
< server-timing: 0=3.94; "Request", 1=2.73; "Logic"
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=1hXaV35z3ympfiksIxvBQIVh5jBT91wzks9M180PFlVQOPHo279vnA2BfubUiEvPA9LtStZLXDdPJPdT83AgN57SW0RlUZzQr38%2BO1v8Q1OudHW4oP7nPSQccp8Ted1xWQXUFOWEzcx7hk8%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 8c643a228a2710db-ORD
<
{
  "message": "connect ECONNREFUSED 172.20.0.48:27017",
  "status": 500
* Connection #0 to host jsonbin.maintainerr.info left intact
}%
```

**Comment by Serph91P** [comment]
> The community rules url in the code doesn't though.
> 
> ```
> ~ > curl -v -H "token 788bfded-1fd0-46e8-8616-28d76e8a2904" https://jsonbin.maintainerr.info/maintainerr-app/rules
> * Host jsonbin.maintainerr.info:443 was resolved.
> * IPv6: 2606:4700:3037::6815:2804, 2606:4700:3034::ac43:acd9
> * IPv4: 172.67.172.217, 104.21.40.4
> *   Trying 172.67.172.217:443...
> * Connected to jsonbin.maintainerr.info (172.67.172.217) port 443
> * ALPN: curl offers h2,http/1.1
> * (304) (OUT), TLS handshake, Client hello (1):
> *  CAfile: /etc/ssl/cert.pem
> *  CApath: none
> * (304) (IN), TLS handshake, Server hello (2):
> * (304) (IN), TLS handshake, Unknown (8):
> * (304) (IN), TLS handshake, Certificate (11):
> * (304) (IN), TLS handshake, CERT verify (15):
> * (304) (IN), TLS handshake, Finished (20):
> * (304) (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 / [blank] / UNDEF
> * ALPN: server accepted h2
> * Server certificate:
> *  subject: CN=maintainerr.info
> *  start date: Jul 25 21:08:35 2024 GMT
> *  expire date: Oct 23 21:08:34 2024 GMT
> *  subjectAltName: host "jsonbin.maintainerr.info" matched cert's "*.maintainerr.info"
> *  issuer: C=US; O=Google Trust Services; CN=WE1
> *  SSL certificate verify ok.
> * using HTTP/2
> * [HTTP/2] [1] OPENED stream for https://jsonbin.maintainerr.info/maintainerr-app/rules
> * [HTTP/2] [1] [:method: GET]
> * [HTTP/2] [1] [:scheme: https]
> * [HTTP/2] [1] [:authority: jsonbin.maintainerr.info]
> * [HTTP/2] [1] [:path: /maintainerr-app/rules]
> * [HTTP/2] [1] [user-agent: curl/8.7.1]
> * [HTTP/2] [1] [accept: */*]
> > GET /maintainerr-app/rules HTTP/2
> > Host: jsonbin.maintainerr.info
> > User-Agent: curl/8.7.1
> > Accept: */*
> >
> * Request completely sent off
> < HTTP/2 500
> < date: Fri, 20 Sep 2024 19:30:25 GMT
> < content-type: application/json; charset=utf-8
> < content-length: 74
> < access-control-allow-origin: *
> < etag: W/"4a-MkwWBrMgISwgXsHeCTALVUl4eao"
> < server-timing: 0=3.94; "Request", 1=2.73; "Logic"
> < cf-cache-status: DYNAMIC
> < report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=1hXaV35z3ympfiksIxvBQIVh5jBT91wzks9M180PFlVQOPHo279vnA2BfubUiEvPA9LtStZLXDdPJPdT83AgN57SW0RlUZzQr38%2BO1v8Q1OudHW4oP7nPSQccp8Ted1xWQXUFOWEzcx7hk8%3D"}],"group":"cf-nel","max_age":604800}
> < nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> < server: cloudflare
> < cf-ray: 8c643a228a2710db-ORD
> <
> {
>   "message": "connect ECONNREFUSED 172.20.0.48:27017",
>   "status": 500
> * Connection #0 to host jsonbin.maintainerr.info left intact
> }%
> ```

you are absolutely right sorry.

**Comment by jorenn92** [comment]
Hey, this issue is related to the web service that hosts the community rules. Unfortunately, the current service seems irrecoverable, so we're in the process of migrating to a new service. However, this will require a new release before the issue can be resolved.

I'm afraid there's no workaround you can apply to the current build to get it working again.

Thanks for your understanding!

**Comment by ydkmlt84** [comment]
This should be fixed now. However, it is a temporary-ish fix. It will work as expected but the backend for Community Rules is not very stable. Which is why we are looking at switching to a new service.

**Comment by gold007eye** [comment]
I can confirm that this is working again as expected.  I will hold the duct-tape on it until the new service is figured out :D

**Comment by ydkmlt84** [comment]
> I can confirm that this is working again as expected.  I will hold the duct-tape on it until the new service is figured out :D

Thank you for your service!

**Comment by ydkmlt84** [comment]
Closing this issue for now, as the Community rules are back up and running. Will need to reopen in the future.

https://status.maintainerr.info is a good resource for Uptime Status.

**Comment by simbasamba** [comment]
This is happening for me now:

`curl -v -H "token 788bfded-1fd0-46e8-8616-28d76e8a2904" https://jsonbin.maintainerr.info/maintainerr-app/rules
* Host jsonbin.maintainerr.info:443 was resolved.
* IPv6: (none)
* IPv4: 172.67.172.217, 104.21.40.4
*   Trying 172.67.172.217:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=maintainerr.info
*  start date: Nov 21 01:58:15 2024 GMT
*  expire date: Feb 19 01:58:14 2025 GMT
*  subjectAltName: host "jsonbin.maintainerr.info" matched cert's "*.maintainerr.info"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* Connected to jsonbin.maintainerr.info (172.67.172.217) port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://jsonbin.maintainerr.info/maintainerr-app/rules
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: jsonbin.maintainerr.info]
* [HTTP/2] [1] [:path: /maintainerr-app/rules]
* [HTTP/2] [1] [user-agent: curl/8.11.1]
* [HTTP/2] [1] [accept: */*]
> GET /maintainerr-app/rules HTTP/2
> Host: jsonbin.maintainerr.info
> User-Agent: curl/8.11.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 404 
< date: Thu, 19 Dec 2024 14:37:55 GMT
< content-type: application/json; charset=utf-8
< content-length: 45
< access-control-allow-origin: *
< etag: W/"2d-KGhd6mPb8VlnwdOhgNLnyEi3Hn8"
< server-timing: 0=6.93; "Request", 1=5.84; "Logic"
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=7rsvCjFLu9M49Eg9OyN56fHedqiGFRmikyNXn8s%2Flpnoq4rnTLdXEJBq7n08XMtsuT0wKBxArDa%2F4sIfYiET6WOCJDYGqScaIplcpoGtK72NDQMPRXeb%2FLSWQ8Zlo%2BAjKhWlCrWRkQhVJOk%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 8f4822239ad1bb15-ZRH
< alt-svc: h3=":443"; ma=86400
< server-timing: cfL4;desc="?proto=TCP&rtt=2307&min_rtt=1831&rtt_var=725&sent=6&recv=8&lost=0&retrans=0&sent_bytes=3403&recv_bytes=777&delivery_rate=1335162&cwnd=246&unsent_bytes=0&cid=d0306108d58ac9eb&ts=377&x=0"
< 
{
  "message": "Not Found",
  "status": 404
* Connection #0 to host jsonbin.maintainerr.info left intact
}⏎  `
