### ISSUE TITLE
Adding Overseerr connection; hostname doesn't work

### ISSUE THREAD

**Issue by SawkeeReemo** [jorenn92/Maintainerr#1292]
When adding a connection to Overseerr, using the hostname (i.e. localhost) doesn't work. It adds http:// to the name in the text box, which normally wouldn't be a problem, but might be a problem here. When I change to IP address, it works fine.

**Comment by ben-propflo** [comment]
Do you mean that the test fails? Are you able to run an nslookup from the container to see if DNS resolution is okay?
`docker exec -it container_name sh -c "nslookup hostname_replace_me"`

**Comment by benscobie** [comment]
Do you mean that the test fails? Are you able to run an nslookup from the container to see if DNS resolution is okay?
docker exec -it container_name sh -c "nslookup hostname_replace_me"

**Comment by SawkeeReemo** [comment]
Ran that command for both localhost and the hostname for my overseerr. Both worked. 

But in the UI config for Maintainerr, if I use either hostname, it adds http://[hostname]/ to the entry. Then localhost does not work, but the hostname for my Overseerr container does. Both are on the same docker network as well. 

And as I’m typing this, I think I just answered my own question and things are working as they should. 🤦‍♂️ 😂

**Comment by ydkmlt84** [comment]
> Ran that command for both localhost and the hostname for my overseerr. Both worked.
> 
> But in the UI config for Maintainerr, if I use either hostname, it adds http://[hostname]/ to the entry. Then localhost does not work, but the hostname for my Overseerr container does. Both are on the same docker network as well.
> 
> And as I’m typing this, I think I just answered my own question and things are working as they should. 🤦‍♂️ 😂

So you are good to go now and this can be closed?

**Comment by SawkeeReemo** [comment]
Yup. All good. Thanks!
