### ISSUE TITLE
Tautullli Integration Fails with HTTP Root Configured

### ISSUE THREAD

**Issue by dreondre** [jorenn92/Maintainerr#1305]
**Describe the bug**

- Tautulli integration does not work when Tautulli has HTTP Root configured. It returns a 404 error.
- It doesn't matter if you set the base URL or not. The error happens when Tautulli has the HTTP Root setting configured. 
- Sonarr and Radarr both support base URL and Tautulli would need the same. 
- Confirmed it works without base URL configured in Tautulli.

**To Reproduce**
1. Go to Settings > Tautulli
2. Configure Tautulli URL, port and API. 
3. Save
4. Test Saved

**Expected behavior**
It's expected that the connection would be successful.

**Screenshots**
```[maintainerr]  |  07/10/2024 12:49:01  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr]  |  07/10/2024 12:49:07  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr]  |  07/10/2024 12:49:16  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr]  |  07/10/2024 12:53:22  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
[maintainerr]  |  07/10/2024 12:53:29  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 404
```

**Device (please complete the following information):**
- Docker
- Maintainerr dc16a13

**Additional context**
- I'm using Docker name resolution and I confirmed that's working fine by running curl from Maintainerr's container shell.

**Comment by ydkmlt84** [comment]
@benscobie Not sure if you saw this or not.
