### ISSUE TITLE
Tiles for Automatic Collections are blank

### ISSUE THREAD

**Issue by macstainless** [jorenn92/Maintainerr#1314]
**Describe the bug**

After I create a rule, the tiles in the Automatic Collections area are blank after the first time I view that page. They're fine the first time I am on the Collections page, but then any time I go back, they're all blank.

**To Reproduce**
1. Create rule.
2. Let collection get created.
3. View collection page. It'll look fine.
4. Leave page and come back any time later. Page will have blank tiles.

**Expected behavior**
Tile contents should be visible. 

**Screenshots**
<img width="1128" alt="SCR-20241009-jpps" src="https://github.com/user-attachments/assets/b91d0ca3-95c1-4b89-85a5-7171b99cfcbe">

**Device (please complete the following information):**
 - OS: This is running in Docker
 - Version 2.1.2 but has been present for multiple versions of the service.

**Additional context**

This may be isolated to Safari on Desktop.

When I go into the inspector, if I disable the CSS 

```
 .overflow-hidden {
/* overflow: hidden; */
}
```

on element `<div class="z-1 absolute inset-0 flex flex-row overflow-hidden">` the tile contents are visible. There's still CSS issues with the text, but the contents are at least readable. 

See attached screen shot:
<img width="2053" alt="SCR-20241009-jtya" src="https://github.com/user-attachments/assets/44cb9fd4-78f4-46ee-bb34-82088c80a8ef">

**Comment by ydkmlt84** [comment]
This is strange behavior, and I haven't seen anyone else have this issue. When the tiles are blank, refreshing the page doesn't do anything?

**Comment by macstainless** [comment]
Refreshing does not resolve the issue. Additionally, I forgot to add this looks to maybe be isolated to Safari on desktop. I haven't tested every browser though.

**Comment by ydkmlt84** [comment]
I am on Edge and haven't had the problem. I don't have the ability to test Safari on desktop.

**Comment by macstainless** [comment]
If you know of a possible reason this could affect only Safari and need me to test any solutions, I'm happy to QA in some fashion.

**Comment by ydkmlt84** [comment]
I will see what I can find and let you know.

**Comment by benscobie** [comment]
@macstainless What version of Safari are you using?

**Comment by macstainless** [comment]
> @macstainless What version of Safari are you using?
> 
> EDIT: I've reproduced on Safari 18

Sorry for the delay in responding. It's 17.3.1 but I see you have already coded a fix for this. THANK YOU!!!
