### ISSUE TITLE
View logs in application

### ISSUE THREAD

**Issue by kage1414** [jorenn92/Maintainerr#1325]
A nice-to-have would be to view the application logs in the application, rather than having to open the currently running docker or vm logs. This could be easily accomplished using a websocket.

Considerations:

- Select logging levels
- Only view logs relating to rules, collections, and the core functionality of Maintainerr (i.e. filter out startup messages, login info, runtime errors, etc.)

**Comment by kage1414** [comment]
I'd be happy to work on this feature request as well once things are a bit more flushed out

**Comment by ydkmlt84** [comment]
> I'd be happy to work on this feature request as well once things are a bit more flushed out

What exactly do you mean when you say "more flushed out"? I understand that Maintainerr isn't perfect but I am curious what would stop you from working on it now, in its current state? Genuinely curious.

**Comment by benscobie** [comment]
I've created a feature request for this here: https://features.maintainerr.info/posts/50/view-logs-in-the-application

**Comment by kage1414** [comment]
> > I'd be happy to work on this feature request as well once things are a bit more flushed out
> 
> What exactly do you mean when you say "more flushed out"? I understand that Maintainerr isn't perfect but I am curious what would stop you from working on it now, in its current state? Genuinely curious.

Sorry, missed this. I assume we don't want all logging available in the application. We would just want to log things like shows that have been deleted, library scanning, things that would be relevant to the user.
