### ISSUE TITLE
Collections not working

### ISSUE THREAD

**Issue by sycot** [jorenn92/Maintainerr#1350]
I have a Rule Set that returns 'true' when looking up an applicable movie, but it's not registered in the corresponding Collection

Please find attached screenshots from the settings screens and docker logs showing successful completion of collection handling.

The instance of Maintainerrr is connected successfully to Plex, radarr and sonarr. I am not using overseer. 

![Screenshot 2024-11-04 214904](https://github.com/user-attachments/assets/f7ad2b14-c917-4d82-91af-ca31446c5a1e)
![Screenshot 2024-11-04 214922](https://github.com/user-attachments/assets/5e48add5-aa53-4ef7-b940-c0aded92adb8)
![Screenshot 2024-11-04 215001](https://github.com/user-attachments/assets/5f3405ba-b194-40bc-a68b-f843d1a0790c)
![Screenshot 2024-11-04 215127](https://github.com/user-attachments/assets/ee7ccfd9-554b-4a9e-8cff-c48ffe4b7434)

 - OS: Ubuntu
 - Version 22.04
 - Docker (26.1.5?) & Docker Compose (2.29.7)

Thank you for any support you are able to provide

**Comment by benscobie** [comment]
Hey @sycot - just want to confirm, are you using 'Run Rules' here or 'Handle Collections'? You'd want to use the former as that one adds media to the collections.

If you are already using that, would you be able to set `DEBUG=true` and re-run so that we get some more info?

**Comment by sycot** [comment]
Ugh, I had a suspicion I was just being a dummy. I was using Handle Collection. I have now also Run Rules and it appears to be working. Thanks for catching my mistake @benscobie
