### ISSUE TITLE
Unable to add rules

### ISSUE THREAD

**Issue by demitrix** [jorenn92/Maintainerr#1351]
**Describe the bug**
Unable to add rules, save button reports no issues, no logging output.

**To Reproduce**
1. Connect Plex/Radarr/Sonarr/Overseerr
2. Click on Rules
3. Click on Add Rule
4. Complete with any combination of settings.

**Expected behavior**
Rule is created.

**Device (please complete the following information):**
 - OS: Official Docker
 - Version 2.2.0

**Additional context**
Rolled back to 2.1.2 and was able to create rule following same procedure.

**Comment by benscobie** [comment]
When you say no logging output, did you check the browser console?

**Comment by demitrix** [comment]
My apologies, I missed the console error, no network request is made since it is erroring on a null value here
`tautulliWatchedPercentOverride: "" != D.current.value ? +D.current.value : void 0,`

**Comment by hwr12** [comment]
I just faced this bug after I installed Maintainerr for the fisrt time and was excited to try it out.
I'm glad you already have fixed it! @benscobie 
Looking forward to see a merge soon
