### ISSUE TITLE
Rule conditions not tested as expected

### ISSUE THREAD

**Issue by DustyTurtleDip** [jorenn92/Maintainerr#1361]
**Describe the bug**
I created a movies rule and when I test it agains a movie, not all conditions are evaluated.

Here's the rules : 
[maintainerr_rule.yaml.txt](https://github.com/user-attachments/files/17707593/maintainerr_rule.yaml.txt)
OR
[maintainerr_rule.yaml.txt](https://github.com/user-attachments/files/17707940/maintainerr_rule.yaml.txt)

When I test the rule against a movie, here's what is tested : 
[maintainerr_rule_test.yaml.txt](https://github.com/user-attachments/files/17707591/maintainerr_rule_test.yaml.txt)

**To Reproduce**
1. Create the rule.
2. Execute the rule in order to create a collection based on it.
3. Go in the collection.
4. Test it against any media.

**Expected behavior**
I am trying to create a collection with the following logic : 
**{** 
  **[ (** releaseDate BEFORE 1080 days **AND** addDate BEFORE 180 days **) AND (** viewCount EQUALS 0 **OR** lastViewedAt BEFORE 60 days **)  ]** 
   **OR**
   **[ (** releaseDate IN_LAST 1080 days **AND** addDate BEFORE 360 days **) AND (** viewCount EQUALS 0 **OR** lastViewedAt BEFORE 60 days **) ] **
**}**

**Device :**
 - OS: Debian
 - Version 12

**Additional context**
Maintainerr is running in Docker

**Comment by benscobie** [comment]
This is expected behaviour, please see the doc note here for details: https://docs.maintainerr.info/Test-Media/?h=test#note-about-test-media-results

If you need help with setting up your rules feel free to head on over to our Discord. We have a rule_help channel and you can search through previous threads for examples 😄
