### ISSUE TITLE
Req: Enhancement. Add 'null' as valid value to select in plex- last view date

### ISSUE THREAD

**Issue by michpas** [jorenn92/Maintainerr#1367]
When using 'plex - last view date' the system allows to select 'amount of days' or 'specific days'.

This all works great, but not in situation where the movie of series hasn't been watched. In this situation plex reports it as: firstValue: null

It would be great if an extra option was added besides 'amounts of days' and 'specific days' that is 'null';

**Comment by benscobie** [comment]
Hi, please see #1071 on how to appropriately raise feature requests. I can see this has been raised a few times in Discord but I cna't see a request for it at the moment. Depending on what you're trying to achieve, you may be able to use a section of **Last view date OR total views = 0**
