### ISSUE TITLE
Request: Delete a show entirely if it has the 'Ended' tag in Sonarr.

### ISSUE THREAD

**Issue by daviddanko** [jorenn92/Maintainerr#1368]
Sonarr has a couple of tags for shows: continuing, upcoming, ended. 

For example, the HBO series Penguin has just ended. Maintainerr will delete correctly the files from the sonarr folder, however, the show will be left in the sonarr webapp forever. Would it be possible to let maintainerr delete the 'ended' shows entirely from sonarr?

**Comment by benscobie** [comment]
Hi, please see #1071 on how to appropriately raise feature requests.
