### ISSUE TITLE
Matching season episodes by Sonarr quality profile ID fails sometimes

### ISSUE THREAD

**Issue by Michael-Busse** [jorenn92/Maintainerr#1395]
**Describe the bug**
When creating a rule that triggers by Sonarr Quality Profile ID (why use ID# and not name here as with Radarr?) (Sonarr - Quality profile ID -> Equals -> Number -> #) it will sometimes flag individual episodes in series outside the specified quality profile ID as matching.

Using the Test Media option a single episode is matched from a show not matching the specified quality profile, but all other epiodes of the same show correctly return false for the match.

**To Reproduce**
1. Go to Rules
2. Click on 'New Rule'
3. Set library to a TV Series library
4. Set type to Episodes
5. Under Rules add a rule with first value: Sonarr Quality Profile ID - Action: Equals - Second Value: Number - Custom Value ID of a quality profile. In my case 9.

I then also have a section/rule that checks if the episode was added more than 365 days ago. But this one works as expected.

**Expected behavior**
Only episodes matching this criteria will show up.

**Device (please complete the following information):**
 - OS: Debian/Docker
 - Version v 5.10.0-21

**Comment by benscobie** [comment]
Would you be able to share a screenshot of the Manage Episodes dialog in Sonarr from a season that has one of these problem episodes?

How comfortable are you with calling APIs using Postman/Insomnia/curl in-case we need to dig a bit further?

**Comment by Michael-Busse** [comment]
Sure - here is Would I lie To You season 16 - where episode 8 shows up in this rule:

![image](https://github.com/user-attachments/assets/22fc80fe-bfbf-4c70-814e-9ccfdb1429f5)

A test of the episode in Test Media:

`- plexId: 51774
  result: true
  sectionResults:
    - id: 0
      result: true
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Sonarr - Quality profile ID
          firstValue: 9
          secondValueName: number
          secondValue: 9
          result: true
    - id: 1
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Plex - Date added
          firstValue: 2023-03-24T22:23:53.000Z
          secondValueName: custom_days
          secondValue: 2023-11-30T10:04:51.772Z
          result: true`

And a test of episode 7 in the same season:
`- plexId: 51628
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Sonarr - Quality profile ID
          firstValue: 3
          secondValueName: number
          secondValue: 9
          result: false
    - id: 1
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Plex - Date added
          firstValue: 2023-02-17T21:24:49.000Z
          secondValueName: custom_days
          secondValue: 2023-11-30T10:06:48.333Z
          result: true`

I'm experienced using REST API using powershell - not so much using curl directly. But I'm sure i can help with rest API output if needed. I used to do these clean-ups with a powershell script, but Maintainerr is much prefered :)
The workaround I use now is to use tags instead of quality profles. And that works perfectly.

**Comment by benscobie** [comment]
So we look at the individual episode to determine the quality profile here, and episode 8 there is HDTV-1080p unlike the others which are WEBDL-1080P.

**Comment by Michael-Busse** [comment]
Yes, I noticed that also. But the quality profile follows the show, not the episodes, as far as I've understood?

**Comment by benscobie** [comment]
You have the type set to Episodes so we look at episode metadata currently: https://github.com/jorenn92/Maintainerr/blob/cca3b0fae36e6939cb51d1c1c83ec8bc7cda6f48/server/src/modules/rules/getter/sonarr-getter.service.ts#L147

We could always introduce a new rule that targets the season/show level in this instance. Feature requests here: https://features.maintainerr.info/

**Comment by Michael-Busse** [comment]
Ah, so in this case it looks at the Plex metadata instead of the sonarr quality profile id? As the quality profile is on the show level and not on the episode level. I see the confusion here.

Tags are working fine for me, so this is a non-issue at the moment. But yes, I may do a feature request for future checks. Thank you for quick feedback :)

**Comment by benscobie** [comment]
It does look at the Sonarr quality profile, just at the episode level. Of course we don't typically think of an episode having a quality profile but they can differ due to upgrades etc.
