### ISSUE TITLE
Discord Link Appears to be invalid

### ISSUE THREAD

**Issue by Kieranwest** [jorenn92/Maintainerr#1396]
Hi I'm looking to get some support with rules to validate if they're setup correctly. 
I tried to join the discord but it looks like the link is invalid / expired. Could this be updated?

**Comment by ben-propflo** [comment]
Are you talking about the one linked under Issues here? That one is working fine for me: https://toolscord.com/invite#WP4ZW2QYwk

**Comment by benscobie** [comment]
Are you talking about the one linked under Issues here? That one is working fine for me: https://toolscord.com/invite#WP4ZW2QYwk

**Comment by ydkmlt84** [comment]
I have verified that the link is valid, and not expired. 
![image](https://github.com/user-attachments/assets/825a65cc-600e-4519-8b0f-96bb00e55be8)
