### ISSUE TITLE
Last viewed date incorrectly parsed if 'null'

### ISSUE THREAD

**Issue by Cheezzhead** [jorenn92/Maintainerr#1406]
**Describe the bug**
When testing for the last viewing date of a media item, if the item has never been viewed by anyone, it reports a value of 'null'. Any comparisons made with a null value fail; as a result, these values are unusable in a practical sense. This is true for both the _Plex - Last view date_ and _Tautulli - Last view date_ rules.

This has been reported [here](https://github.com/jorenn92/Maintainerr/issues/1367) and [here](https://github.com/jorenn92/Maintainerr/discussions/531) already. First off, I believe this behavior is moreso a bug than a feature request. Additionally, I'm aware that there are workarounds available by adding more rules (i.e. adding _OR Tautulli - Total views = 0_), however as the complexity of a ruleset grows, this becomes unfeasible (at least until some kind of parenthesis operators are added).

Practically speaking, the only *truly* weird behavior is with the 'before' comparison (which, incidentally, is also the most popular use-case for this rule) as it always fails if the last viewing date reports null. In my opinion, when a user creates a rule akin to 'include media whose last view date was longer than X days ago', then he **obviously** expects to include media items that have never been watched. In fact I can scarcely think of a scenario where this *isn't* the users' intention (though I'm happy to be proven wrong).

**Expected behavior**
Media items that have never been watched should always succeed a 'Last view date before X days' rule.

**Device (please complete the following information):**
 - OS: Ubuntu (docker)
 - Version 2.2.1

**Comment by benscobie** [comment]
> In my opinion, when a user creates a rule akin to 'include media whose last view date was longer than X days ago', then he obviously expects to include media items that have never been watched. In fact I can scarcely think of a scenario where this isn't the users' intention (though I'm happy to be proven wrong).

With this a newly added item would be picked up straight away, so you would need to pair it with something like Date Added, so it's not much better than having Total views = 0, no? Users that don't want the new behaviour you describe (no matter how rare it is) won't have a way to opt out of it.

> however as the complexity of a ruleset grows, this becomes unfeasible (at least until some kind of parenthesis operators are added).

Rules are essentially already parenthesis operators. I think the real issue here is that the rules UI is quite painful to work with and is something I want to address.

My current line of thinking is implementing something similar to Home Assistant's automation UI:
![image](https://github.com/user-attachments/assets/22e2791f-72fd-4158-92d7-1829cdba1309)

**Comment by ydkmlt84** [comment]
Adding to this...last viewed date of never isn't always what people are looking for. If it always succeeded when it was null, then something that wasn't ever watched would always match. Not everyone wants to get rid of something that wasn't watched, but instead wants to only get rid of it if it hasn't been watched in a certain time frame.

I personally think the added `Total Views = 0` is giving you even more control, where making it always match is taking away options.

The UI definitely doesn't help the situation either, but I think taking away options isn't a good idea.

**Comment by Cheezzhead** [comment]
> With this a newly added item would be picked up straight away, so you would need to pair it with something like Date Added, so it's not much better than having Total views = 0, no? Users that don't want the new behaviour you describe (no matter how rare it is) won't have a way to opt out of it. Your desired behaviour seems to assume that a person has a Date Added condition, but we cannot always assume that.

Ah yes you're right, I didn't consider this scenario. 

This problem is more nuanced, then, but imo definitely still a problem; because I still think that adding a condition where one of the values can be 'null' without any way to test for it or exclude it explicitly is semantically and syntactically incomplete. There are indeed use-cases (like the one you describe) where the value of 'null' leading to a false result happens to be the desired behavior, but really that's a matter of coincidence, because there are *also* plenty of examples where this is not the case. The fact that most solutions essentially boil down to 'add another condition to make sure' is emblematic of this incompleteness.

And really this goes for any condition that can have a possible value of 'null'. If there is no way to test for it (i.e. with an 'exists' or 'not exists' parameter, optional, whatever) there will by definition always be gaps in our reasoning of a media item.

And yeah, definitely agree re: a more intuitive UI.

> Adding to this...last viewed date of never isn't always what people are looking for. If it always succeeded when it was null, then something that wasn't ever watched would always match. Not everyone wants to get rid of something that wasn't watched, but instead wants to only get rid of it if it hasn't been watched in a certain time frame.

Well I was specifically talking about the condition with the 'before' comparison operator, obviously I don't think that a condition with the 'equals' operator should always match if one of the operands is 'null'.

**Comment by benscobie** [comment]
I think we're in agreement here 😄 I've raised a feature request for NULL comparison here with a reference to this issue: https://features.maintainerr.info/posts/54/add-comparison-with-null-values

The UI work I mentioned isn't raised as a feature, but it's on my list to look at.

Both of those should hopefully resolve your pain points. I'll close this for now as we'll leave the rule as-is.
