### ISSUE TITLE
Tatulli integration with Movies (times viewed) not working

### ISSUE THREAD

**Issue by richardquick** [jorenn92/Maintainerr#1417]
I have setup Tatulli integration for both TV shows and Movies and i'm unable to get Movies to work correctly.  Note the difference of TIMES VIEWED vs TOTAL VIEWS in the rules of TV vs Movies.  I have confirmed that Movies being flagged by the rule do have a viewing number greater than 0 in Tautulli.

Tv Shows (working as expected)
Plex
Date added
before
amount of days
90
AND
Tatulli
Total views
equals
number
0

Movies (Not seeing total views correctly)
Plex
Date added
before
amount of days
90
AND
Tatulli
Times Viewed
equals
number
0

**Comment by benscobie** [comment]
>  I have confirmed that Movies being flagged by the rule do have a viewing number greater than 0 in Tautulli.

Can you confirm the watch percentage of one of those movies? It will only count as a view if it's over the configured threshold which is set in Tautulli Settings -> General -> Watched Percent & Video Watched Completion Behaviour, OR the threshold configured under Tautulli watched percent override in the rule. The circle on the far right of the history row will be fully white when it's reached Tautulli's threshold.
