### ISSUE TITLE
Latest version showing out of date

### ISSUE THREAD

**Issue by benscobie** [jorenn92/Maintainerr#1443]
v2.3.1 shows out of date when it's the latest version. 

We need to tweak how the version gets loaded as the monorepo update broke this.

**Comment by themarkwilliams** [comment]
Could the version number be added in the Maintainerr version box even if app thinks the version is out of date? 

![image](https://github.com/user-attachments/assets/6b405688-5770-4aef-97ce-52f97e4ed0b8)

I couldn't find the version elsewhere in the UI and thought my docker update was failing.

**Comment by 0penSourcerer** [comment]
> Could the version number be added in the Maintainerr version box even if app thinks the version is out of date?
> 
> ![image](https://private-user-images.githubusercontent.com/17816123/397550872-6b405688-5770-4aef-97ce-52f97e4ed0b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODE2NDksIm5iZiI6MTczNDY4MTM0OSwicGF0aCI6Ii8xNzgxNjEyMy8zOTc1NTA4NzItNmI0MDU2ODgtNTc3MC00YWVmLTk3Y2UtNTJmOTdlNGVkMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3NTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MDBjNTNhZTJiMmQ5YmFiMmE0ZDhiNmQ2NTQ1ZTdmMWY5ZGRjY2Y3NGRmMGNiYzlkZGNiYWQ2ZTg0NWM1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rnipT2amCcAuGLNuxjQmgt9SZRLEp8iQR3VA96Dfne8)
> 
> I couldn't find the version elsewhere in the UI and thought my docker update was failing.

I would also like to see this.
