### ISSUE TITLE
Rules for TV-Show libraries always go back to "Show" in "Media Type"

### ISSUE THREAD

**Issue by nilleiz** [jorenn92/Maintainerr#1445]
**Describe the bug**
Rules for TV-Show libraries always go back to "Show" in "Media Type"

**To Reproduce**
Go to a rule for a TV-Show library and set its Media Type to Season or Show.
Click Save
Go to the same rule again.
Media Type set back to Show.
This also happens when creating new rules.

**Expected behavior**
Keep set Media Type

**Screenshots**

**Device (please complete the following information):**
 - OS: Docker
 - Version 2.3.1

**Additional context**

**Comment by benscobie** [comment]
Thank you, we're aware, there's a PR here to fix it just needs reviewing: https://github.com/jorenn92/Maintainerr/pull/1444
