### ISSUE TITLE
v2.4.0 Maintainerr is not running on Synology (DSM7.2) Container Manager

### ISSUE THREAD

**Issue by Sn3ider** [jorenn92/Maintainerr#1451]
**Describe the bug**
Maintainerr image updated on the 20th of December 2024 (v2.4.0), and maintainerr is no longer starting.
Maintainerr worked before this update (v2.3.1).

**To Reproduce**
Steps to reproduce the behaviour:
1. image: jorenn92/maintainerr:latest had been updated on the 20th of December
2. Container Manager is now showing the container as not runnable
3. Error message coming up as: Error: Format string 'PORT=%(ENV_UI_PORT)s,HOSTNAME=%(ENV_UI_HOSTNAME)s' for 'environment' contains names ('ENV_UI_PORT') which cannot be expanded. Available names: ENV_DEBUG, ENV_GIT_SHA, ENV_HOME, ENV_HOSTNAME, ENV_NODE_ENV, ENV_NODE_VERSION, ENV_PATH, ENV_TZ, ENV_UV_USE_IO_URING, ENV_VERSION_TAG, ENV_YARN_CACHE_FOLDER, ENV_YARN_GLOBAL_FOLDER, ENV_YARN_INSTALL_STATE_PATH, ENV_YARN_VERSION, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:ui' (file: '/etc/supervisord.conf')

**Expected behavior**
Maintainerr should run without any issues after the update. 

**Screenshots**
N/A

**Device (please complete the following information):**
 - OS: Synology DSM
 - Version 7.2.2

**Additional context**
Rolling back to 2.3.1 resolved the issue.

**Comment by benscobie** [comment]
I can't see any changes between 2.3.1 and 2.4.0 that would cause this issue, those environment variables were added in 2.3.0.

Does it start okay if you declare these environment variables:
UI_PORT=6246
UI_HOSTNAME=0.0.0.0

**Comment by Sn3ider** [comment]
@benscobie This seems to be the fix. Strange that with the v2.3.1 I have not declared these variables in the YAML file.

**Comment by benscobie** [comment]
I do wonder what other default environment variables are missing for you... would you be able to run this command inside your container and paste the output? `printenv`

**Comment by Sn3ider** [comment]
@benscobie I only ran the default YAML with the path changes when created the Project in Container Manager.
![image](https://github.com/user-attachments/assets/9b5153bc-6a4c-4f23-99e3-6eb9e8e81d7f)

**Comment by benscobie** [comment]
Well the other environment variables are in there, so I'm not sure why those weren't 🤷
