### ISSUE TITLE
Overseerr URL not parsing correctly in 2.4.0

### ISSUE THREAD

**Issue by 2fst4u** [jorenn92/Maintainerr#1453]
**Describe the bug**
When setting the overseerr URL, it is not parsed correctly and fails to connect.

**To Reproduce**
1. Install fresh
2. Configure overseerr URL, in my case `overseerr-service.overseerr` with port `80` and API key set.
3. Debug logs show `[maintainerr] | 21/12/2024 18:51:32  [DEBUG] [OverseerrApi] GET request to undefined/api/v1/status failed: TypeError: Invalid URL`

Note "undefined" instead of the set value.

**Expected behavior**
Maintainerr connects to overseerr

**Device (please complete the following information):**
 - OS: Ubuntu docker 
 - Version 2.4.0

**Comment by 2fst4u** [comment]
It's doing it for tautulli too


`[maintainerr] | 21/12/2024 19:01:13  [DEBUG] [TautulliApi] GET request to null/api/v2?apikey=null&cmd=get_tautulli_info failed: TypeError: Invalid URL
`

**Comment by 2fst4u** [comment]
Weird, it worked after the fifty thousandth time. I saved before testing (which shouldn't be necessary) and it worked now.

**Comment by smitstay** [comment]
I just had the same issue. After seeing you were able to get it to work, I was able to narrow down the issue. If you use your cursor to move to the next input it doesn't register the value in the url field, however, if you tab to move to the next input it will work. 

Hopefully, that helps someone else with the same problem
