### ISSUE TITLE
Tautulli and Overseer not connecting

### ISSUE THREAD

**Issue by Shah-do** [jorenn92/Maintainerr#1473]
Adding the hostname ports and API doesn't connect them, even though radarr and sonarr connected perfectly
here's the screenshot of the logs
![image](https://github.com/user-attachments/assets/86242276-d9f9-4e59-8bf5-5f9b0702c0c1)

**Comment by Shah-do** [comment]
the ip , port and the api key 
![image](https://github.com/user-attachments/assets/2e2c2d1a-959f-41d5-94b5-c74e7b57ad47)

**Comment by benscobie** [comment]
Are you saving the details before trying Test Saved?

**Comment by Shah-do** [comment]
I am so stupid I am sorry

**Comment by ydkmlt84** [comment]
> I am so stupid I am sorry

It is all good. It is a common oversight. Today, I added some more verbiage to the connection failure message that addresses the fact that you have to save before testing. So, I believe if that was there earlier, you would have seen it and known what to do.
