### ISSUE TITLE
Collection generation crash

### ISSUE THREAD

**Issue by 8a8al00ey** [jorenn92/Maintainerr#378]
**Describe the bug**
When creating a collection it crashes

**To Reproduce**
1. Go to 'Rules'
2. Click on 'Run Rules'
3. See error

**Expected behavior**
Be able to run rules an not crash

```
/opt/server/dist/modules/rules/rule-executor.service.js:114
        let collection = await this.collectionService.getCollection(rulegroup.collectionId);
                                                                              ^

TypeError: Cannot read properties of undefined (reading 'collectionId')
    at RuleExecutorService.handleCollection (/opt/server/dist/modules/rules/rule-executor.service.js:114:79)
    at RuleExecutorService.executeAllRules (/opt/server/dist/modules/rules/rule-executor.service.js:88:32)

Node.js v18.13.0

Failed to proxy http://localhost:3001/api/collections/media?collectionId=7 Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3001
}
```

**Additional context**
Running a rule against a very large library

**Comment by jorenn92** [comment]
Hi there, Thanks for your report!

I've already done some improvements a while back that might fix this issue.
They didn't make it into a release yet, but are available in the 'jorenn92/maintainerr:develop' image.

Could you try this image and report back if the issue still persists?

Thanks in advance!

**Comment by jorenn92** [comment]
I made a release containing the changes mentioned above. 
Could you try version 1.4.0 and report back please?

**Comment by jorenn92** [comment]
I'm closing this issue. If the problem still persists, please create a new issue and link to this one. 
Thanks!
