### ISSUE TITLE
Unmonitor (without delete) in Sonarr

### ISSUE THREAD

**Issue by nemchik** [jorenn92/Maintainerr#450]
**Is your feature request related to a problem? Please describe.**
The options for Sonarr Actions on a TV library only include deleting.

**Describe the solution you'd like**
I would like to see the ability to just unmonitor without deleting anything.

This may be worth a separate issue, but I think rules for unmonitoring based on:

- unmonitor episode if air date is X days in the past
- unmonitor season if all listed episodes air dates are X days in the past (and no episodes are listed as future or undownloaded)
- unmonitor show if all episodes air dates are X days in the past (and no episodes are listed as future, or undownloaded, and the show status is listed as ended)

some of that may already be doable, but i don't see episode air date as an option to unmonitor individual episodes in the rules available for sonarr.

**Describe alternatives you've considered**
I haven't really considered an alternative

**Additional context**
Part of the reason I want to unmonitor instead of delete is i'd like to setup two separate rules. one to unmonitor after X period (and watch status and request status and all that fun stuff from the example rules) and another to delete after a much longer period.

**Comment by jorenn92** [comment]
Hi, thanks for your report! I'll look into this.
Adding the option to unmonitor only does indeed sound like a useful addition. 

I'll also check if I can add the 'episode air date' Sonarr rule.

**Comment by jorenn92** [comment]
Hi, I added the functionality to only unmonitor media without deletion. 

I created issue #457 for the request to add more control over individual seasons & episodes, since this is a bigger change (but a necessary one) .
