### ISSUE TITLE
[Feature Request] Sonarr Season Delete

### ISSUE THREAD

**Issue by nebb00** [jorenn92/Maintainerr#453]
Would it be possible to only delete TV shows in sonarr as a whole. Rather than individual episodes?

**Comment by jorenn92** [comment]
Hi, 

I believe that option is already there. The only options for shows currently are: 

- Delete the entire show
- Unmonitor in Sonarr & delete files for the entire show (future seasons will still be added)
- Unmonitor in Sonarr & delete files for all seasons that you currently have

There's also a reques to add the option to only unmonitor in Sonarr without deletion. (#450)

**Comment by nebb00** [comment]
Let me reword. If i had a show with two seasons, and a rule to remove if last viewed over a year ago.

Season 1: Last Viewed Date = 01-01-2022
Season 2: Last Viewed Date = 04-08-2023

Would the whole show be left, as Season 2 has been last viewed under a year. Or can we delete Season 1 only?

**Comment by jorenn92** [comment]
That's clearer, thanks!

Currently, it will keep the show until the view date of all episodes, regardless of the season, was longer than a year ago. 

I would personally also like more control over the individual seasons. I will definitely be working on that, but I'm currently not yet sure what the best way forward is. It would require a rework of the current behavior & probably break current rules.

**Comment by jorenn92** [comment]
This will be tracked in:  #457
