### ISSUE TITLE
[Feature Request] Extend show functionality for more control over individual seasons/episodes

### ISSUE THREAD

**Issue by jorenn92** [jorenn92/Maintainerr#457]
Currently, shows are only handled as a whole and rules are evaluated against all current episodes. 
Alter this behavior so there's more control over individual episodes & seasons. 

This was requested in #450 but deserves it's own issue.

For instance: 
- unmonitor/delete episode if air date is X days in the past
- unmonitor/delete season if all listed episodes air dates are X days in the past
- unmonitor/delete entire show if all episodes air dates are X days in the past

**Comment by CyberOxide** [comment]
Got your message...you want me to test some thing out?
