### ISSUE TITLE
[Question] Media not found when Overseerr - Requested by user (username) is used

### ISSUE THREAD

**Issue by kiwi3007** [jorenn92/Maintainerr#465]
**Describe the bug**
Media not found when Overseerr - Requested by user (username) is used rules alongside custom values. This is the case when using all Actions.

**To Reproduce**
1. Create a rule with the first value Overeerr - Requested by user (username)
2. Select any action, e.g. NOT_EQUALS
3. Select Second value as text
4. Enter a username (I have tried plex username, Overseerr username, email, and even Overseerr user ID)
5. Results will contain the same number of media items as it would without the rule in place.

In

**Expected behavior**
Requests from that user are either included or excluded based on the chosen action.

**Screenshots**
![image](https://github.com/jorenn92/Maintainerr/assets/18101735/03e2c1b1-d281-4fce-b91c-3f9c9d50f63a)

**Device (please complete the following information):**
 - OS: UnRaid
 - 6.12.4-rc19

**Comment by jorenn92** [comment]
Hi, thanks for your report!

It’s odd that you’re not able to find/exclude media requested by a specific user. I also use this in my own rules and didn’t notice an issue.

The ‘Overseerr - Requested by user (username)’ value returns a Plex username, so it should’ve worked when using the Plex user.

Note that the user is case-sensitive, is it possible the case didn’t match 100%?

If a case mismatch isn’t the issue, is there anything in the logs that might give an indication to what is?

**Comment by kiwi3007** [comment]
Plex Username with correct case works, thank you. Perhaps it could be made clearer that the username is the Plex one? And the matching could ignore case?

**Comment by jorenn92** [comment]
Okay great!

I’ll make it’s description a bit clearer in a future release.
