### ISSUE TITLE
[Question] Add image to https://github.com/walkxcode/dashboard-icons

### ISSUE THREAD

**Issue by powerdude** [jorenn92/Maintainerr#477]
**Is your feature request related to a problem? Please describe.**
Not really, just use homepage as my dashboard and would be nice to load the image from here.

**Describe the solution you'd like**
Upload the image

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by ydkmlt84** [comment]
This is probably something you could do yourself. The icons are here in the files, and you would just need to add a pull request to their repo. At the very least, I believe this feature request should go on walkxcode's repo.

**Comment by jorenn92** [comment]
Closing this issue since action needs to be taken on walkxcode's side. If you want them to add it, you should submit a pull request or issue on their project.
