### ISSUE TITLE
[Feature request] Option to add list exclusion when delete from Radarr/Sonarr

### ISSUE THREAD

**Issue by appiekap653** [jorenn92/Maintainerr#487]
**Is your feature request related to a problem? Please describe.**
When you choose to delete movie from Radarr or series from Sonarr and you have setup some lists to auto-import, the movie or series will get downloaded and imported back again rights away after Maintainerr deleted it.

**Describe the solution you'd like**
When choosing delete as option instead of unmonitor, let a checkbox option appear like this:

- [ ] Add list exclusion for items

The API for both Radarr and Sonarr already support this.

**Comment by jorenn92** [comment]
Good find! 
 
 I was about to push a release. But since this is an easy addition, I added this feature first. 
 
 I'll do some testing, if all goes well I'll release it later today.
