### ISSUE TITLE
autodelete watched

### ISSUE THREAD

**Issue by foXaCe** [jorenn92/Maintainerr#532]
Hello, I would like to create a rule that automatically deletes episodes after being seen in plex.
Is that possible ?

**Comment by jorenn92** [comment]
Hi,

Sure, there are a couple of ways you could accomplish this. The simplest would be :
- Set media type to episodes
- Add rule: Plex total views - BIGGER - number 0

**Comment by foXaCe** [comment]
ok thansk you

and this ?

![image](https://github.com/jorenn92/Maintainerr/assets/290678/b7e3a7c6-4e79-47a8-bc5b-f5535513fdf2)

**Comment by jorenn92** [comment]
That means Maintainerr will delete/unmonitor (depending on your other choices) media that has lived in the collection for at least 30 days. You might want to read the documentation, these options are explained in there.

**Comment by foXaCe** [comment]
yes sorry 😪

**Comment by jorenn92** [comment]
> yes sorry 😪

No worries, just trying to point you in the right direction.
