### ISSUE TITLE
[BUG] Maintainerr UI becomes unresponsive after job execution.

### ISSUE THREAD

**Issue by Quafley** [jorenn92/Maintainerr#538]
**Describe the bug**
When I execute the jobs, most of them go right. But there is a job which generates an error which causes the UI to throw this into the console:

**To Reproduce**
I think the steps can be reproduced by creating the following rule:
![image](https://github.com/jorenn92/Maintainerr/assets/44779473/403fba95-8308-44ac-8fb5-0149685578e4)
(irregular is set by a script of mine, which will tag a sonarr release if it's irregular e.g., season 1 4 5.

**Expected behavior**
Rule execution.

**screenshots:**
![image](https://github.com/jorenn92/Maintainerr/assets/44779473/450f2373-c960-4a9e-a514-60f57e941ef2)
(for all tabs)

**Error when jobs are executed**
```
19/10/2023
10:11:13
/opt/server/dist/modules/rules/rule-executor.service.js:306
19/10/2023
10:11:13
                ? val2.map((el) => el.toLowerCase())
19/10/2023
10:11:13
                                      ^
19/10/2023
10:11:13
19/10/2023
10:11:13
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
19/10/2023
10:11:13
    at /opt/server/dist/modules/rules/rule-executor.service.js:306:39
19/10/2023
10:11:13
    at Array.map (<anonymous>)
19/10/2023
10:11:13
    at RuleExecutorService.doRuleAction (/opt/server/dist/modules/rules/rule-executor.service.js:306:24)
19/10/2023
10:11:13
    at RuleExecutorService.executeRule (/opt/server/dist/modules/rules/rule-executor.service.js:289:31)
19/10/2023
10:11:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19/10/2023
10:11:13
    at async RuleExecutorService.executeAllRules (/opt/server/dist/modules/rules/rule-executor.service.js:80:37)
19/10/2023
10:11:13
19/10/2023
10:11:13
Node.js v18.18.0
19/10/2023
10:11:13
error Command failed with exit code 1.
19/10/2023
10:11:13
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19/10/2023
10:11:30
Failed to proxy http://localhost:3001/api/collections Error: connect ECONNREFUSED 127.0.0.1:3001
19/10/2023
10:11:30
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
19/10/2023
10:11:30
  errno: -111,
19/10/2023
10:11:30
  code: 'ECONNREFUSED',
19/10/2023
10:11:30
  syscall: 'connect',
19/10/2023
10:11:30
  address: '127.0.0.1',
19/10/2023
10:11:30
  port: 3001
19/10/2023
10:11:30
}
```

```
Failed to proxy http://localhost:3001/api/settings Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3001
}
Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3001
}
```
**Job in question:**

**Device (please complete the following information):**
 - OS: Docker - unRAID
 - Version [e.g. current]

**Comment by jorenn92** [comment]
Hi, thanks for this bug report! 

It seems like you managed to crash the server portion of Maintainerr. The reason being that one of your media items returned an array containing an undefined value for one of your rule values.

I'll include extra null checks and wrap the container's UI & server processes in a supervisor, so they'll be restarted in case of a hard crash.

For now, I suggest you deactivate the rulegroup until a fix is available. You could also try to identify the media item that causes this, but I don't really know a way to find it without debugging the code...
