### ISSUE TITLE
Sonarr errors pulling shows

### ISSUE THREAD

**Issue by bulfinch** [jorenn92/Maintainerr#546]
**Describe the bug**
When creating a rule which has a value that pulls information from Sonarr. That interaction with Sonarr returns an error for some shows. 
This is seen in the logs as 

[Nest] 124  - WARN [SonarrApi] Error retrieving show by tvdb ID
[Nest] 124  - WARN [SonarrApi] Object:
{
  "label": "Sonarr",
  "errorMessage": "Request failed with status code 400",
  "tvdbId": null
}

**To Reproduce**
1. Create a rule which users Sonarr for a first value. 
2. Here I created Sonarr - tags show, but the problem is with any sonarr rule.
3. Run Rule 

**Expected behavior**
The error is somewhat obvious, "Error retrieving show" but it doesn't identify which show it is. This prevents an accurate running of the rule. 

**Screenshots**
![image](https://github.com/jorenn92/Maintainerr/assets/46585568/534e713a-0d4b-46be-a7c8-b03af7087046)

![image](https://github.com/jorenn92/Maintainerr/assets/46585568/97d43e56-1a4a-470d-b76f-9eb3ef19506f)

**Device (please complete the following information):**
 - ubuntu 22.04 LTS
 - Maintainer Docker latest tag 
 - Sonarr 4.0.0.697develop (docker)

As this rule is run, Maintainerr returns 66 shows, but there are 82 shows that have this tag. "local"

**Comment by jorenn92** [comment]
Hi, thank you for this report!.

When Maintainerr checks a Sonarr / Radarr rule value, it has to first fetch the tmdb / tvdb ID. Mostly, this is available in the Plex response. But for some shows, Plex doesn't have these IDs. When that happens, there are a few fallback mechanisms to still find the tvdbid for the show. We need this ID, because we can't query the Sonarr api without it. 

These fallback mechanisms appear to have failed for 16 of your shows.
Could you give me 2 or 3 example shows that failed? These are good cases to toughen this fallback system.

**Comment by bulfinch** [comment]
Thanks for the response. Here are some of the shows. 

Twisted Metal (2023) https://thetvdb.com/series/twisted-metal
Under the Queen's Umbrella (2023) https://thetvdb.com/series/under-the-queens-umbrella
Halfway Home (2007) https://thetvdb.com/series/halfway-home
Domina (2021) https://thetvdb.com/series/domina
One Piece (2023) https://thetvdb.com/series/one-piece-2022

**Comment by jorenn92** [comment]
> Thanks for the response. Here are some of the shows.
> 
> Twisted Metal (2023) https://thetvdb.com/series/twisted-metal Under the Queen's Umbrella (2023) https://thetvdb.com/series/under-the-queens-umbrella Halfway Home (2007) https://thetvdb.com/series/halfway-home Domina (2021) https://thetvdb.com/series/domina One Piece (2023) https://thetvdb.com/series/one-piece-2022

Thanks!

I've been trying to replicate this, but unfortunately i don't see the same behavior.
I added both 'Domina' & 'One Piece' to my server, and both got a tvdb ID in the Plex API response when running Maintainerr.

My theory is that Plex servers don't update its metadata that often and will include the data that was available when the show was added. The tvdb ID was probably missing when you added it to your Plex instance. This is just a guess, though, I'm not sure how it works exactly.

I added some extra fallback logic, so hopefully that's enough to catch this case. I also improved the logs a bit, when this happens you should now see the name of the show that failed.

It would be a huge help if you could report the result after the next release. Thanks in advance!

**Comment by bulfinch** [comment]
> > Thanks for the response. Here are some of the shows.
> > Twisted Metal (2023) https://thetvdb.com/series/twisted-metal Under the Queen's Umbrella (2023) https://thetvdb.com/series/under-the-queens-umbrella Halfway Home (2007) https://thetvdb.com/series/halfway-home Domina (2021) https://thetvdb.com/series/domina One Piece (2023) https://thetvdb.com/series/one-piece-2022
> 
> Thanks!
> 
> I've been trying to replicate this, but unfortunately i don't see the same behavior. I added both 'Domina' & 'One Piece' to my server, and both got a tvdb ID in the Plex API response when running Maintainerr.
> 
> My theory is that Plex servers don't update their metadata that often and will include the data that was available when the show was added. The tvdb ID was probably missing when you added it to your Plex instance. This is just a guess, though, I'm not sure how it works exactly.
> 
> I added some extra fallback logic, so hopefully that's enough to catch this case. I also improved the logs a bit, when this happens you should now see the name of the show that failed.
> 
> It would be a huge help if you could report the result after the next release. Thanks in advance!

Wanted to report back that this looks good. The error returns as tvdb id. The one error i have now was the result of a mismatched show. A show named Anna was a 2022 show in sonarr but a different Anna (2021) in Plex.

**Comment by jorenn92** [comment]
> > > Thanks for the response. Here are some of the shows.
> > > Twisted Metal (2023) https://thetvdb.com/series/twisted-metal Under the Queen's Umbrella (2023) https://thetvdb.com/series/under-the-queens-umbrella Halfway Home (2007) https://thetvdb.com/series/halfway-home Domina (2021) https://thetvdb.com/series/domina One Piece (2023) https://thetvdb.com/series/one-piece-2022
> > 
> > 
> > Thanks!
> > I've been trying to replicate this, but unfortunately i don't see the same behavior. I added both 'Domina' & 'One Piece' to my server, and both got a tvdb ID in the Plex API response when running Maintainerr.
> > My theory is that Plex servers don't update their metadata that often and will include the data that was available when the show was added. The tvdb ID was probably missing when you added it to your Plex instance. This is just a guess, though, I'm not sure how it works exactly.
> > I added some extra fallback logic, so hopefully that's enough to catch this case. I also improved the logs a bit, when this happens you should now see the name of the show that failed.
> > It would be a huge help if you could report the result after the next release. Thanks in advance!
> 
> Wanted to report back that this looks good. The error returns as tvdb id. The one error i have now was the result of a mismatched show. A show named Anna was a 2022 show in sonarr but a different Anna (2021) in Plex.

Thanks for the feedback! I’ll close this issue. If you run into anything else, feel free to open a new issue / discussion.
