### ISSUE TITLE
[Feature Request] Sonarr - Delete all but latest Season

### ISSUE THREAD

**Issue by Animosity022** [jorenn92/Maintainerr#574]
**Is your feature request related to a problem? Please describe.**
I might be missing this as I did try to look around, but in Sonarr, a common workflow I have is not based on time but based on the 'monitor latest season as I want to keep the latest season of a show.

**Describe the solution you'd like**
My work is monitor the latest season, delete all the old seasons by unmonitoring them in Sonarr and deleting them from disk manually. I do spend time remembering to go back when new seasons happen.

**Describe alternatives you've considered**
Sonarr Episode Trimmer used to work but is very old and only worked on x number of episodes rather than latest season.

**Additional context**

**Comment by jorenn92** [comment]
Hey, you'll have to figure out a rule that manages what you'd like to accomplish. 
I added the 'Is (part of) latest aired / airing season' rule in PR https://github.com/jorenn92/Maintainerr/pull/576 to help you out a bit. This rule is only available for seasons & episodes.

After release, you can use this with a 'false' boolean value, then it'll return all seasons that are not the latest.

**Comment by Animosity022** [comment]
Oh that's perfect! Appreciate the quick response and help! I'll give it a test.

**Comment by Animosity022** [comment]
I tested the develop branch and works perfect. I used something pretty simple like to define my monitored 'last' seasons:

![image](https://github.com/jorenn92/Maintainerr/assets/5088712/bb0a97f7-a5d7-4bd9-9fb4-aedece778aef)

Collection updates properly and looks great! Thanks for the quick fix!
