### ISSUE TITLE
No images on overview

### ISSUE THREAD

**Issue by X-static** [jorenn92/Maintainerr#583]
**Describe the bug**
The movie posters images are not showing on the overview page.

![Screenshot_2023-11-08-23-28-12-377_com vivaldi browser](https://github.com/jorenn92/Maintainerr/assets/3238301/81a70a91-b622-4f56-a6c0-39649045f4e4)

**To Reproduce**
1. Go to 'Overview'
2. There are no pictures on movies

**Expected behavior**
Movie posters being visible.

**Screenshots**

**Device (please complete the following information):**
 - OS: Ubuntu
 - Version 18.4
 - docker container

**Additional context**

**Comment by jorenn92** [comment]
Hey, thanks for your report.

Maintainerr needs internet access to fetch images from tmdb. Is it possible that Maintainerr is running in a subnet without an outside connection?

**Comment by X-static** [comment]
Hi. Does seem to be the case. I just pinged google.com inside the container console and reached it successfully.

**Comment by jorenn92** [comment]
That's odd, could you check the network requests in your browser's developer console? Each image should be a server request. What's the response & response code? 

Are you using the amd64(x86) version of the images? Or are you running an arm device? 

If you're using the amd64 version, you could temporarily use the 'develop' docker tag, there's an unreleased fix that adds the UI's error logs to the container output. There's no database changes yet, so if you're currently running latest, you could change it back afterward without issues. (staying on develop could cause issues in the future though)

**Comment by X-static** [comment]
I'm using amd64. I tried the develop tag but no changes.

I quickly checked the developer console on my PC and the images have a failed to load resource error with the code ERR_CONNECTION_RESET if I recall correctly. Is there anything you'd like me should check when I'm back on PC?

**Comment by jorenn92** [comment]
Hey, sorry for this late reply. 

You could try to copy the URL of an image request and paste it in another browser tab. Do you see the image or does that also fail? 
Does this happen on each device you try to open Maintainerr's UI?

**Comment by X-static** [comment]
![image](https://github.com/jorenn92/Maintainerr/assets/3238301/31732737-1ffb-42f6-a6c0-ef688ac86385)

Not sure if this is just the console or the actual URL, but the special characters are showing as the encoded hexadecimal equivalent.

I only tested on a windows pc and android phone, but is happening on both.

**Comment by jorenn92** [comment]
That's the correct URL, The encoded chars in the dev tool are normal. 
When you copy the full URL and paste it in a new browser window, do you see the image? 

You could also try to only copy the value after 'url=' from this url, that's the call the server actually makes to tmdb (this is the real image source). Does that return an image?

**Comment by X-static** [comment]
The full URL doesn't work. The part after 'url=' and before '&w=1080&q=75' works if I replace the encoded characters with the correct ones.

**Comment by jorenn92** [comment]
I'm not sure if this could be a possible solution, but i implemented the change documented in https://nextjs.org/docs/app/api-reference/components/image#remotepatterns. Maintainerr was still using the 'domains' approach, but that'll be deprecated in NextJS 14.  

If this doesn't work, I'm actually at a loss. This is something on NextJS's side (I just use their image optimization/caching mechanism), but I can't figure out what's going wrong.

**Comment by X-static** [comment]
I tried the develop image and still no pictures.

**Comment by jorenn92** [comment]
This addresses a Next/image issue observed in certain installations, where the server crashes and instantly reboots upon requesting a cached image. Although the exact trigger is not definitively identified, I have introduced a solution that allows users to configure the image caching behavior (https://github.com/jorenn92/Maintainerr/commit/078625eb22c8b1c121c3e08173180f1ecb3e0d68). By disabling this setting, images will now be sourced directly from tmdb rather than being cached by next/image.

**Comment by X-static** [comment]
It's working now. Thank you so much!

**Comment by X-static** [comment]
You might need to do the same thing here. Inside the collection it's working.

<img width="477" alt="image" src="https://github.com/jorenn92/Maintainerr/assets/3238301/0c31649f-25eb-419c-b52e-2cb6d22e2c5e">

**Comment by jorenn92** [comment]
Oh i see, thanks for the heads up!

**Comment by jorenn92** [comment]
Fixed in 1.6.10
