### ISSUE TITLE
Action CONTAINS / NOT_CONTAINS not producing expected result 

### ISSUE THREAD

**Issue by bulfinch** [jorenn92/Maintainerr#588]
**Describe the bug**
This rule is used to evaluate if a show/movie is part of an existing Plex collection. 
Operator `AND`
First value `Plex - Collections media is present in (list of titles)`
Action `CONTAINS` or `NOT_CONTAINS`
Second value `Text` 
Custom value `some value that is part of the name of a collection`

**To Reproduce**
1. Create a rule using these values for a collection present in the Plex library. eg. A show library has a collection called `IMDb Top 250`. The Goal is to evaluate is a show is in this collection. In this example I would want to exclude the show from being removed so I created the rule. 
Operator `AND`
First value `Plex - Collections media is present in (list of titles)`
Action `NOT_CONTAINS`
Second value `Text` 
Custom value `IMDb`
2. When the collection is created, a show contained in this collection will have been added. 
3. IF the action and custom value are changed to 
Action `NOT_EQUALS`
Custom value `IMDb Top 250`
the created collection works as expected and the show would be excluded. 

**Expected behavior**
I expected `CONTAINS` `NOT_CONTAINS` to evaluate the words in the titles of existing Plex collections. While using `EQUALS` seems like an obvious fix, I have a large library with Collections such as Oscars Best Picture Winners, Oscars Best Director Winners, Oscars Winners 2017, etc. Being able to create a rule that evaluates all collections containing the word Oscars would be easier. 

**Screenshots**
In this example, focus on Bluey using `NOT_CONTAINS` and a partial collection title 
![image](https://github.com/jorenn92/Maintainerr/assets/46585568/e9c43404-cc02-422d-8695-5d7f3b853cf2)
![image](https://github.com/jorenn92/Maintainerr/assets/46585568/d7111e7f-d2f0-41e5-bcef-3214ff098e55)
![image](https://github.com/jorenn92/Maintainerr/assets/46585568/d3933958-0e8e-4a52-9baf-1812ea567c73)
vs `NOT_EQUALS` and full title. 
![image](https://github.com/jorenn92/Maintainerr/assets/46585568/bfa01bf9-f0bd-4131-b28e-79ccf1084273)
![image](https://github.com/jorenn92/Maintainerr/assets/46585568/9077ffad-5f94-4852-bf19-f6a00c8ec4f1)

**
Device (please complete the following information):**
 - OS: Ubuntu
 - Version Docker:latest

**Comment by bulfinch** [comment]
I spent some time thinking about this and if `CONTAINS EXACT` or `CONTAINS PARTIAL` is better, and my thought is maybe an improvement but most likely more confusion. I come at this from a dumb user perspective, not a smart engineer, and just take the words to mean literary what they say. So if I see in a list of choices, and there's `contains exact` this seems obvious, but if there is also `contains` and `contains partial` I become confused as to the distinction, and I know nothing of arrays and comparative lists. Not great feedback I know, and thank you for the work you have put in.

**Comment by jorenn92** [comment]
Thank you for your feedback. It would probably look something like CONTAINS (exact match) and CONTAINS (Partial match) in the selection dropdown. CONTAINS(exact match) would replace the current CONTAINS option.

**Comment by jorenn92** [comment]
This is available since release 1.6.8, closing this issue.
