### ISSUE TITLE
Issue with baseurl configured with Sonarr/Radarr - API hits not going through and giving 303s

### ISSUE THREAD

**Issue by Animosity022** [jorenn92/Maintainerr#598]
**Describe the bug**
I was testing out the new rule with only keeping the latest season and that works well, but when I go to handle the collection, it says it deleted / unmonitored it from Sonarr, but that never happens.

**To Reproduce**
1) Create a rule that has a delete with 0 days
2) Run rule
3) Validate in Sonarr

**Expected behavior**
Delete and Unmonitor the season/episodes

**Screenshots**

**Device (please complete the following information):**
Unraid Docker / 1.6.8

**Additional context**
```
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [CollectionWorkerService] Start handling all collections.
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [CollectionWorkerService] Handling collection 'Old Seasons Going Away - Home'
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [CollectionWorkerService] Handling collection 'Old Seasons Going Away - Home' finished
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [CollectionWorkerService] Handling collection 'Old Seasons Going Away - Other'
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [CollectionsService] Removing media with id 134924 from collection..
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [PlexApiService] Removed collection from Plex
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [SonarrApi] Unmonitored season(s) 48 from Sonarr show with ID 331
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [CollectionWorkerService] [Sonarr] Removed season 48 from show 'Saturday Night Live'
[Nest] 128  - 11/14/2023, 11:44:13 AM     LOG [CollectionWorkerService] Handling collection 'Old Seasons Going Away - Other' finished
[Nest] 128  - 11/14/2023, 11:44:20 AM     LOG [CollectionWorkerService] All collections handled. Triggered Overseerr's availability-sync because media was altered
```

But when I check Sonarr:

![image](https://github.com/jorenn92/Maintainerr/assets/5088712/e76d9d6a-4c52-4eca-a9f9-9f00db7172ac)

I don't see any log traffic on Sonarr either at the same time. I'm confuged with Plex/Overseerr/Sonarr/Radarr and they all test out ok.

**Comment by Animosity022** [comment]
I've tried with both season and episode but left it on episode in the rule for now:

![image](https://github.com/jorenn92/Maintainerr/assets/5088712/c935a3d3-bb72-46f8-8ad6-69e3d3f2291d)

**Comment by jorenn92** [comment]
I just tried this with a season and that appears to have worked, are you using Sonarr V4 or V3? I only test with a V3 instance. The API endpoints should be the same, but perhaps something's broken with V4

**Comment by Animosity022** [comment]
V3 - I usually avoid betas:

Version
3.0.10.1567

I'm not even seeing a request hit Sonarr, any other things I should check?

**Comment by jorenn92** [comment]
Is Sonarr's debug logging enabled? Otherwise the API logs won't show. 
You could try to create a simple test rule that checks a Sonarr value (Sonarr - is monitored equals true, for instance). Does that generate logs in Sonarr (and adds the correct media to the collection)?

**Comment by Animosity022** [comment]
Here are the two logs.

```
[Nest] 128  - 11/14/2023, 1:54:29 PM     LOG [CollectionWorkerService] Handling collection 'Old Seasons Going Away - Other'
[Nest] 128  - 11/14/2023, 1:54:29 PM     LOG [CollectionsService] Removing media with id 134924 from collection..
[Nest] 128  - 11/14/2023, 1:54:29 PM     LOG [PlexApiService] Removed collection from Plex
[Nest] 128  - 11/14/2023, 1:54:30 PM     LOG [SonarrApi] Unmonitored season(s) 48 from Sonarr show with ID 331
[Nest] 128  - 11/14/2023, 1:54:30 PM     LOG [CollectionWorkerService] [Sonarr] Removed season 48 from show 'Saturday Night Live'
[Nest] 128  - 11/14/2023, 1:54:30 PM     LOG [CollectionWorkerService] Handling collection 'Old Seasons Going Away - Other' finished
```

and sonarr side.

```
root@gemini:/mnt/appssd/appdata/sonarr/logs# grep DELETE sonarr.debug.txt
2023-11-14 13:54:30.1|Debug|Api|[DELETE] /api/v3/episodefile/249160?apikey=(removed) 303.SeeOther (0 ms)
```

Hmm, the 303 seems odd too. I'll dig a little more.  I think it's because I have a baseurl /sonarr in my setup and that's confusing it.

**Comment by Animosity022** [comment]
Yep, the baseurl is what does it. I took that off for a quick test and deleted proper.

![image](https://github.com/jorenn92/Maintainerr/assets/5088712/7d58c98d-17ef-45d0-a547-ff4c85d19162)

**Comment by Animosity022** [comment]
I use a baseurl for Sonarr and Radarr:

![image](https://github.com/jorenn92/Maintainerr/assets/5088712/3dcf1439-7981-44ed-88ec-76c3afedbe6c)

**Comment by Animosity022** [comment]
I removed the baseurls and everything is working as expected as it's an easy change for me.

**Comment by jorenn92** [comment]
Aha, good find! Does Sonarr, by configuring this, expect calls to go to /sonarr/api/v3 when you've got this configured? I'm not really sure why it wouldn't work with this setting active.

**Comment by Animosity022** [comment]
Correct.

Overseerr has a box for base url in the settings for Radarr/Sonarr:

![image](https://github.com/jorenn92/Maintainerr/assets/5088712/0acac379-1048-477f-829c-85edee1400f4)

**Comment by jorenn92** [comment]
I made the base URL configurable in https://github.com/jorenn92/Maintainerr/pull/603. This feature will be accessible in the upcoming release, or it can be utilized immediately in the current development image.
