### ISSUE TITLE
[Bug] Can't connect to Sonarr/Radarr on Kubernetes

### ISSUE THREAD

**Issue by kenlasko** [jorenn92/Maintainerr#628]
**Describe the bug**
I am unable to connect to Sonarr/Radarr on my K3S cluster.  If you're not familiar with it, the way it works in Kubernetes is that you can connect directly to services (exposed IP addresses) from within the same namespace.  

I have services setup called sonarr-service, radarr-service etc.  All my other *arr apps are able to communicate by connecting to **http://sonarr-service:8989** or **sonarr-service:8989** etc. However, Maintainerr throws a Connection Failed error for Sonarr/Radarr. Plex and Overseerr both work fine connecting via **plex-service** and **overseerr-service**.

When I connect to the Maintainerr container directly, I am able to connect to all the services using nc: 
```
/opt # nc -zv sonarr-service 8989
sonarr-service (10.43.35.222:8989) open
``` 

**To Reproduce**

1. Go to Settings - Sonarr
2. Enter either http://sonarr-service  or sonarr-service or sonarr.service.media-tools.svc.cluster.local or any variation
3. Enter 8989 for Port
4. See error:  Connection failed! Please check and save your settings

**Expected behavior**
I expect Maintainerr to connect successfully to Sonarr/Radarr

**Screenshots**

**Device (please complete the following information):**
 - K3S v1.27.7+k3s2

**Comment by kenlasko** [comment]
When I test the settings, I get the Connection Failed message in the URL, but I don't get an equivalent warning in the logs. However, when I change the hostname to something that is definitely wrong, I get this in the logs:

```
WARN [SonarrApi] Couldn't fetch Sonarr info.. Is Sonarr up?
```
It seems that it is at least partially aware that the connection is valid.  I created a simple rule to test if the connection was actually working, but I got this error when I executed the rule:
```
LOG [RuleExecutorService] Not all applications are reachable.. Skipped rule execution
```

**Comment by kenlasko** [comment]
Yes, I can certainly help! Just tell me what to do.

**Comment by jorenn92** [comment]
Hey sorry, i lost track of this issue.. If you're still up for it, do you use Discord? If so you may send me a PM and we can discuss details.

**Comment by kenlasko** [comment]
I have a Discord account. Don't use it much, though. How do I contact you?

**Comment by bjw-s** [comment]
What happens when you try and connect over the FQDN? `sonarr.<your_namespace>.svc.cluster.local:8989`? It could be a known Alpine (musl) DNS issue (https://github.com/k3s-io/k3s/issues/6132) causing your issue.

**Comment by kenlasko** [comment]
Nope. Tried the full service FQDN as well with no luck. What's curious is that both Plex and Overseerr connections work with just the service names (ie: http://overseerr-service and http://plex-service). Its only Radarr/Sonarr.  @jorenn92, happy to reach out to you on Discord once you give me a link! :)

**Comment by jorenn92** [comment]
> Nope. Tried the full service FQDN as well with no luck. What's curious is that both Plex and Overseerr connections work with just the service names (ie: http://overseerr-service and http://plex-service). Its only Radarr/Sonarr that don't work with any combination of formats. @jorenn92, happy to reach out to you on Discord once you give me a link! :)

Hey, sorry again, i’ve had a busy few days.. On our Github homepage is a Discord icon, when you click on it you’ll be invited to the public discord channel. You’ll find me there in the members list and you’ll be able to pm me.

**Comment by poloniumTacos** [comment]
Just want to say I ran into this issue on 2.0 I ended up saving all the radarr/sonarr/overseerr/plex settings and restarting the container. Came back and re-tested and it worked lol

**Comment by jorinator** [comment]
Gettings the same errors when I execute the test, on all services. When I do what @ghost said (saving, rebooting, then testing again), it completes the test successfully.

**Comment by matthiasnm** [comment]
Just commenting for anyone that might have the issue i did. I am using traefik with all my containers and was getting the error "[WARN] [RadarrApi] Couldn't fetch Radarr info.. Is Radarr up?" So I tried what5 ghost said and it worked but I had to tweak radarr and sonarr instead of the IP I put the hostname and it worked.

**Comment by ubun2Junky** [comment]
I'm running Traefik, Maintainerr (2.2.1), Plex, Overseerr, Tautulli, Radarr and Sonarr all under Unraid.  I stopped and restarted the Maintainerr container several times and keep getting the  "Connection Failed!  Please check and save your settings" message whenever I click on the 'Test Saved' button.  I've checked the logs but don't really see anything there.  This was the last entry.  Perhaps I'm looking at the wrong logs?  

`[maintainerr] | 16/12/2024 23:35:36  [INFO] [NestApplication] Nest application successfully started`

Overseerr, Plex and Tautulli all connect just fine with the IP address of the Unraid server.  I disabled docker all together on Unraid and enabled it back up, but I'm still getting the mentioned message for both Sonarr and Radarr.  I have tried both the IP address and the service name, but I'm still getting the same message as before.  Any advice would be appreciated!

**Comment by ubun2Junky** [comment]
@benscobie, thank you for your reply.  I forced an update on my unraid server and it seems to have downloaded the latest version.  I deleted my previous configuration for both Radarr and Sonarr and added them again.  It seems that this time around the base url did not default to ‘/‘ and that was what caused the previously mentioned error.  Having the base url as ‘/‘ for Tautulli does not seem to be a problem, but Radarr and Sonarr does not like it. Thx!

**Comment by matthiasnm** [comment]
Were you able to get it connected? So some more info for my situation. Since I am using traefik I have all my containers running off of the traefik proxy network I created. Since you are using unraid idk what your setup looks like but check to see if yours is similar to mine, because if it is all you need to do is put the container name in the host field the port number and click save. Dont click test. After you have saved it restart maintainerr and than try clicking test. This is what worked for me. It will be dependent on your setup if it works or not.

**Comment by ubun2Junky** [comment]
@matthiasnm, thank you for the heads up.  My issue was that I had a '/' on the base url.  Once I removed that Maintainerr was able to connect.  I tried with the service name (container name) and with the IP address of the Unraid host and the corresponding port number and both ways connected without issue.
