### ISSUE TITLE
[FEATURE REQUEST] Change "Media deleted after days" to clarify action that will execute

### ISSUE THREAD

**Issue by mrsdoubtfire613** [jorenn92/Maintainerr#629]
**Is your feature request related to a problem? Please describe.**
Not related to an issue.  The Rule General option of "Media deletion after days" does not change even when the selected Sonarr/Radarr action selected does NOT involve media deletion.

**Describe the solution you'd like**
The text could be changed to "<Sonarr or Radarr> Action taken after days" so it's clear that media won't be deleted if "Unmonitor show and keep files" is selected.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jorenn92** [comment]
The parameter was renamed with release 2.0.0
