### ISSUE TITLE
[Feature Request] JellySeer Integration

### ISSUE THREAD

**Issue by ViktorLindgren95** [jorenn92/Maintainerr#658]
**Is your feature request related to a problem? Please describe.**
Currently Maintainerr dosent have JellySeer Support even tho JellySeer is a Fork of Overseer

**Describe the solution you'd like**
Maintainarr Dosent seem to connect to JellySeer even tho its a Fork

**Describe alternatives you've considered**
I cannot use OverSeer as it dosent suppott JellyFin

**Comment by ViktorLindgren95** [comment]
Im taking an uneducated guess that it shouldnt be that much of an issue to make them work together as JellySeer is 80% the same code as Overseerr

**Comment by jorenn92** [comment]
If their API’s match, it shouldn’t be that much of a problem to integrate it. But is a Jellyseerr integration useful without Jellyfin support?

**Comment by ViktorLindgren95** [comment]
You are right and I'm looking into just biting the bullet and migrating to plex .

But for the usecase jellyseer x plex, that would be super useful !

**Comment by Fallenbagel** [comment]
> If their API’s match, it shouldn’t be that much of a problem to integrate it. But is a Jellyseerr integration useful without Jellyfin support?

The api is the same. Only difference is jellyfin specific apis. If you use plex with jellyseerr there's virtually no difference between overseerr and jellyseerr

**Comment by samip5** [comment]
I was able to connect to Jellyseer with Maintainerr.

**Comment by jorenn92** [comment]
> I was able to connect to Jellyseer with Maintainerr.

And does it work as expected? I presume that not all API endpoints are accessible.

**Comment by samip5** [comment]
> > I was able to connect to Jellyseer with Maintainerr.
> 
> And does it work as expected? I presume that not all API endpoints are accessible.

I'm not sure how it should work with it to begin with so not sure?
