### ISSUE TITLE
Multiple instance of Radarr and Sonarr support

### ISSUE THREAD

**Issue by mduijm** [jorenn92/Maintainerr#663]
Hi,

I see I can only configure one instance of both apps, while I have them twice (normal + 4k). 

Would it be possible to add support in Maintainerr for this? Same as Overseerr ;) 

thanks!

**Comment by jorenn92** [comment]
Hey, there's already an open FR for this feature (#461). I'll work on it at some point in the future. In the meantime, you'd have to set up two Maintainerr instances.
