### ISSUE TITLE
The port used differs from the docs

### ISSUE THREAD

**Issue by 2fst4u** [jorenn92/Maintainerr#694]
I have just spun up a fresh instance and spent a while digging to figure out that the port used is 8080, which is different to 8154 shown in the readme. Not a big issue but it's surely likely to trip someone else up.

**Comment by jorenn92** [comment]
Hey, what do you mean exactly? Port '8154' mentioned in the documentation is just a suggestion. You have the flexibility to configure it however you prefer, as long as it's mapped to the internal port '80'.
