### ISSUE TITLE
Sonarr show ended flagging continuing shows as well

### ISSUE THREAD

**Issue by richardquick** [jorenn92/Maintainerr#718]
When adding a rule against TVShows and using the rule of:
Sonarr - Show ended
Equals
Sonarr - Show ended

The collection is flagging items that sonarr shows as continuing.  When looking at TVBD the show also shows as continuing.

Example show that flagged as ended but is continuing.  There are many more but this is just an example.
https://thetvdb.com/series/bering-sea-gold

**Comment by jorenn92** [comment]
Well, you're comparing the same values with each other. It would be a bug if they weren't equal.

What you want is this:

```
Sonarr - Show ended
Equals 
Boolean 
True (or false, if you want continuing shows)
```
