### ISSUE TITLE
Pi4 arm/v8 support

### ISSUE THREAD

**Issue by hippytyre** [jorenn92/Maintainerr#754]
**Is your feature request related to a problem? Please describe.**
Hello, is it possible to run this on a Pi4? I'm running armf on dietpi, I notice some of the forms mention an arm/v7 version

**Describe the solution you'd like**
support for a pi4

Thanks

**Comment by jorenn92** [comment]
At one time, the armv7 build was functional, but it no longer works. Despite my efforts to resolve the issue, the build keeps getting stuck at downloading packages. I decided to cease my attempts and removed all references to armv7.

You might consider building the image on your Raspberry Pi yourself; there's a chance it could work for you. (If it works please let me know, maybe it was just a cross compile issue..)

**Comment by hippytyre** [comment]
I'm a noob when it comes to docker but I'll give building my own image a go. I have this running now ...

docker build https://github.com/jorenn92/Maintainerr.git

No errors so far!

**Comment by hippytyre** [comment]
ah well, it was worth a try.

ERROR: failed to solve: process "/bin/sh -c yarn run build:ui" did not complete successfully: exit code: 1


Thanks for your help, I'll just have to wait until my new NAS arrives.

**Comment by jorenn92** [comment]
> ah well, it was worth a try.
> 
> ERROR: failed to solve: process "/bin/sh -c yarn run build:ui" did not complete successfully: exit code: 1
> 
> Thanks for your help, I'll just have to wait until my new NAS arrives.

What was the specific error message you encountered? It's possible that I'm familiar with it. At least you made progress; I didn't even reach the point of building the apps.

**Comment by jorenn92** [comment]
Btw, doesn't the arm64 image work on the pi 4? I was always under the impression it did.

**Comment by hippytyre** [comment]
> Btw, doesn't the arm64 image work on the pi 4? I was always under the impression it did.

Aha! It does, all I have to do was specify the platform in the compose file. Although, now it's running and built I cannot access it, no ip shown in portainer for the stack.
