### ISSUE TITLE
[Feature Request] Rules don't match for Overseer Local Users

### ISSUE THREAD

**Issue by corotte** [jorenn92/Maintainerr#795]
**Describe the bug**
The 'Overseerr - Requested by user (Plex username)' rule criteria only bind to Plex users and does not match for Overseerr local managed users.

**To Reproduce**

**Create a new rule**
Use the 'Overseerr - Requested by user (Plex username)' rule criteria for a Plex user listed in Overseerr
Verify that there are shows/film requested by Plex user and check result in collection (there should be some listed)
Modify rule to be a Overseerr local user
Verify that there are shows/film requested by Overseerr Local user and check result in collection (there should none listed)

**Expected behavior**
We should be allowed to made rules based on Overseerr local users

**Device**
OS: Linux Mint 21.2 Cinnamon
latest released docker image 1.7.1

**Additional context**
I got some Plex local user that have a Overseerr local user and i can't made rule based on Overseerr local user.
There is also another request for Plex Local user ( #644 ) but it does not talk about Overseerr local user since Plex local user are not sync in Overseerr

**Comment by jorenn92** [comment]
The app would always attempt to match Overseerr users with Plex users, which naturally wouldn't function for local Overseerr users. This issue has been addressed in PR #822.
