### ISSUE TITLE
Movie exists in Plex, but not in Radarr, so is skipped and count is reset

### ISSUE THREAD

**Issue by patheticaesthetic94** [jorenn92/Maintainerr#799]
**Describe the bug**
When reaching the point of deletion, the system will attempt to unmonitor the movie in question from Radarr. Not all of the movies in my collection were created in Radarr and some exist from before I had these tools. There shouldn't be a need for 2 seperate rules when the movies that are returned are a mix of those that exist in Radarr and those that don't.

Is it designed behaviour if the movie exists in Plex, but not in Radarr, to be skipped and have the count reset? Why is the Radarr step not skipped if it doesn't exist? I still want the movie to be deleted regardless.

**To Reproduce**
1. Create a rule which includes movies that do not exist in Radarr and is set to unmonitor and delete
2. Wait for deletion day
3. Note that the CollectionWorkerService refuses to remove the movie from Plex because it can't unmonitor anything in Radarr
4. Note that count resets in Maintainerr

**Expected behavior**
If the movie cannot be found in Radarr to unmonitor, then the rest of the steps should continue as expected and the movie should be deleted from Plex.

**Device (please complete the following information):**
 - OS: Ubuntu
 - ARM

**Additional context**
[Nest] 132  - 01/25/2024, 12:00:00 AM     LOG [CollectionsService] Removing media with id 88805 from collection..
[Nest] 132  - 01/25/2024, 12:00:01 AM     LOG [CollectionWorkerService] Couldn't find movie with tmdbid 877269 in Radarr. No action taken for movie with Plex ID: 88805

**Comment by jorenn92** [comment]
Hey, thanks for your feedback!

I set it up that way originally because I figured something is probably off when an item is missing from an app, so I did it intentionally. But you might have a point that this isn't ideal, and there could be situations where you'd want it to keep going even if that happens.
