### ISSUE TITLE
Stuck Processing Rules

### ISSUE THREAD

**Issue by Droppisalt** [jorenn92/Maintainerr#821]
**Describe the bug**
When I select "Run rules" in the rules menu, it adds these lines to my log and then nothing seems to happen. Any clue what's going on?

```
LOG [RuleExecutorService] Starting Execution of all active rules.
LOG [RuleExecutorService] Executing rules for 'Delete Watched Movies'
```

**Device (please complete the following information):**
 - OS: unraid
 - Version: jorenn92/maintainerr:latest

**Comment by jorenn92** [comment]
How extensive is your library? Processing might take some time with large libraries. It's also possible that it's completed and is no longer active. Ideally, it should notify you when it's finished, but that doesn't always happen with the current release.
