### ISSUE TITLE
[Bug] Error when creating a collection from TV show seasons

### ISSUE THREAD

**Issue by patheticaesthetic94** [jorenn92/Maintainerr#826]
**Describe the bug**
When creating a rule to delete TV show seasons, viewing the collection that is created returns the following error message. There are no attributed logs, only information in the browser console.

`Application error: a client-side exception has occurred (see the browser console for more information).`

**To Reproduce**
1. Create a rule which will return TV show seasons which will be unmonitored and deleted
2. Run the rules so that the collection is filled. Mine has 30 results.
3. Upon opening, note that a faint text box is shown in black font with the error noted above
4. Open the browser console and observe the error as shown in my screenshot

**Expected behavior**
The results of the rules should be shown as per all other collections. The posters should appear rather than an error.

**Screenshots**
<img width="1512" alt="Screenshot 2024-02-02 at 15 31 41" src="https://github.com/jorenn92/Maintainerr/assets/4212801/dbe475ba-f548-44c1-8b41-1c3445ec581e">

**Device (please complete the following information):**
 - OS: Ubuntu
 - ARM

**Comment by jorenn92** [comment]
Is this on version 2.0.0 released today?

**Comment by patheticaesthetic94** [comment]
Yes, and versions before this. I found an alternative in the form of just deleting the entire show - but thought it may have been fixed in 2.0.0. Unfortunately not 😢

**Comment by jorenn92** [comment]
I don't think i've received a similar report, so nothing was changed in this regard with 2.0.0. 

Can you determine which media item is causing this issue? One method is to inspect network requests and examine the 'parentData' entry for each item. Look for any entries missing this data or lacking a GUID, as this could be the culprit.

Is it conceivable that the show was added or removed after Maintainerr initially collected it? If the ID changed within Plex, this might explain the problem.

**Comment by patheticaesthetic94** [comment]
I've just gone through the 24 entries that show up in the Network tab and all of them have their parentData entry. Nothing looks out of the ordinary. I'll be happy to work my way through the shows that appear and manually delete them to see if I can work out what one might be possibly causing this.

**Comment by jorenn92** [comment]
> I've just gone through the 24 entries that show up in the Network tab and all of them have their parentData entry. Nothing looks out of the ordinary. I'll be happy to work my way through the shows that appear and manually delete them to see if I can work out what one might be possibly causing this.

And do they all have the Guid property inside parentData?

i know how to fix it, but it would be great if we could figure out why it’s lacking 🤔

**Comment by patheticaesthetic94** [comment]
I can confirm that every single entry has a Guid property within parentData. Very strange!

Although, I think i've worked out what the issue is. Some of my content is from 'ye olden days' before Plex properly moved away from the TVDB to their own metadata system. 

Anything that is a guid that doesn't start with 'plex://' seems to fail. After updating the metadata for one of the shows still using this old system, the problem fixed itself.

**Comment by jorenn92** [comment]
Hmm, i see. Thanks for figuring this out! I’ll have to dig deeper into it. Even if that happens, the UI should not fail.

**Comment by jorenn92** [comment]
Could you try to replicate the issue with the develop image once https://github.com/jorenn92/Maintainerr/pull/848 is merged? That PR includes a possible solution.

**Comment by patheticaesthetic94** [comment]
Ah, see the issue is that I have updated all my metadata now to use the new Plex format so I'm not entirely sure how I would be able to. I definitely would if I could though!
