### ISSUE TITLE
v2 in unprivileged mode can't use docker volumes

### ISSUE THREAD

**Issue by mwsmith824** [jorenn92/Maintainerr#827]
**Describe the bug**
We had a docker volume configured for the sqlite database that mounted as /opt/data. Even with the files set to the new user (1000:1000) the server would exit with a warning about unprivileged mode in the new version and stop. 

**To Reproduce**
1. Adjust the default compose file to use a docker volume that mounts as /opt/data
2. docker compose up -d
3. See error in logs as server exits

**Expected behavior**
Load the database through the docker volume like a standard mount

**Device (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by jorenn92** [comment]
Make sure the parent data folder also has the correct permissions. Maintainerr will test it’s read/write access to the data folder and to the database file, if existing. If either fails, it’ll complain.

**Comment by mwsmith824** [comment]
That did it. My apologies.

**Comment by jorenn92** [comment]
> That did it. My apologies.

No problem, glad it worked out!

**Comment by jorenn92** [comment]
> I am facing similar issue. Using arrs and ran sudo chown 1000 /location/where/my/data/is but am still getting a permission error. Any help w/ troubleshooting is greatly appreciated, I love this app! Logs below:
> 
> 2024-02-16 19:19:10,751 INFO exited: server (exit status 0; expected) 2024-02-16 19:19:11,754 INFO spawned: 'server' with pid 3017 2024-02-16 19:19:12,754 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs) THE CONTAINER NO LONGER OPERATES WITH PRIVILEGED USER PERMISSIONS. PLEASE UPDATE YOUR CONFIGURATION ACCORDINGLY: https://github.com/jorenn92/Maintainerr/releases/tag/v2.0.0 Could not create or access (files in) the data directory. Please make sure the necessary permissions are set 2024-02-16 19:19:13,834 INFO exited: server (exit status 0; expected) 2024-02-16 19:19:14,836 INFO spawned: 'server' with pid 3035 2024-02-16 19:19:15,837 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs) THE CONTAINER NO LONGER OPERATES WITH PRIVILEGED USER PERMISSIONS. PLEASE UPDATE YOUR CONFIGURATION ACCORDINGLY: https://github.com/jorenn92/Maintainerr/releases/tag/v2.0.0 Could not create or access (files in) the data directory. Please make sure the necessary permissions are set 2024-02-16 19:19:16,882 INFO exited: server (exit status 0; expected) 2024-02-16 19:19:17,884 INFO spawned: 'server' with pid 3053

Make sure you also chown the directory itself, not just the files in it. Not sure if it's your issue, but it's a common mistake

**Comment by NeurekaSoftware** [comment]
I ran into this issue too. Can we make it so we don't need to chown the parent directory? i.e. `/var/lib/docker/volumes/media-server_maintainerr/_data`. The working directory should be enough. This really feels like it goes against the grain in terms of how docker manages volumes.
