### ISSUE TITLE
Failure to fetch latest GitHub version crashes the UI

### ISSUE THREAD

**Issue by jorenn92** [jorenn92/Maintainerr#887]
Reported on Discord:

I have maintainerr running but as soon as i go to the web interface to set the settings for Plex i'm getting this error. Anybody an ID? The webinterface keeps refreshing as a madman because of this.

https://cdn.discordapp.com/attachments/1152219250291920929/1205789137085399070/image.png?ex=65d9a5a4&is=65c730a4&hm=8142e651cfd663db30b332a734cfb38adf121c715472aad98cbaa5e8ae8d7313&

**Comment by myrison** [comment]
Same experience here.  I installed for the first time today and am not able to get past the configuration because of this.

**Comment by DaftFuzz** [comment]
Found a temporary workaround by going into the maintainerr.sqlite database with 

`sqlite3 maintainerr.sqlite`

And then running

`update settings set plex_hostname = '';`

The client-side is complaining due to the hostname being null, so just setting it to empty allows the UI to load and for you to actually set it up.

**Comment by myrison** [comment]
Thanks @DaftFuzz , that did it! 

> Found a temporary workaround by going into the maintainerr.sqlite database with
> 
> `sqlite3 maintainerr.sqlite`

**Comment by jorenn92** [comment]
> Found a temporary workaround by going into the maintainerr.sqlite database with
> 
> `sqlite3 maintainerr.sqlite`
> 
> And then running
> 
> `update settings set plex_hostname = '';`
> 
> The client-side is complaining due to the hostname being null, so just setting it to empty allows the UI to load and for you to actually set it up.

Thanks for pointing me in the right direction! Up until now i though it had something to do with the version indicator failing to talk with the GitHub API. I figured it out though and will push an emergency release.
