### ISSUE TITLE
Cannot connect to other containers (Radarr/Sonarr)

### ISSUE THREAD

**Issue by anast20sm** [jorenn92/Maintainerr#888]
I have all dockers in the same docker-compose file and I cannot connect maintainerr to sonarr or radarr as I do with other tools (by image name either by IP)

Could you please help me connect them? Thanks in advance!

**Comment by jorenn92** [comment]
That should work, i’ve been using it that way myself. You can try to: 

- put http:// in front of your hostname (http://radarr)
- Make sure you save first before testing
- Try to exec in the container and use curl to test if the container is able to reach the apps

if it still fails, could you share a screenshot?

**Comment by anast20sm** [comment]
Solved! Sorry, put only hostname/ip and not thought on http/s due it said only hostname/ip.
Sorry for the silly question!
