### ISSUE TITLE
Help needed, changing  privileged port from 80 to 6246 in CA Docker

### ISSUE THREAD

**Issue by velvetpants1975** [jorenn92/Maintainerr#913]
Hi, Im still fairly new to Docker and had been running this in UnRaid through the Community App store.
The latest update killed my web UI for me and I saw the changelog about the privileged port changing, but I am unsure of where I would update this in the Docker Image settings in the UnRaid UI.
Thanks for any tips or help, love this app so far!

**Comment by jorenn92** [comment]
Hey, there’s this pinned GitHub discussion with Unraid’s upgrade instructions:

https://github.com/jorenn92/Maintainerr/discussions/851

**Comment by velvetpants1975** [comment]
Very nice, thanks for the help!
