### ISSUE TITLE
Store sqlite database separate from media data

### ISSUE THREAD

**Issue by dphildebrandt** [jorenn92/Maintainerr#931]
**Is your feature request related to a problem? Please describe.**
By storing the sqlite db alongside the media data this makes docker backups and data snapshotting/backups a bit more messy

**Describe the solution you'd like**
It would be great to store the sqlite file under not /opt/data but somewhere else. Something like:

```
volumes:
      - $MEDIA_DIR:/opt/data
      - $MAINTAINERR_DOCKER_DIR:/opt/config
```

**Describe alternatives you've considered**
Ive tried something like 

```
volumes:
      - $MEDIA_DIR:/opt/data
      - $MAINTAINERR_DOCKER_DIR/maintainerr.sqlite:/opt/data/maintainerr.sqlite
```

But there is still a symlink in the media data dir

**Comment by jorenn92** [comment]
What exactly do you mean by media data? Only the sqlite database and logs directory are present in /opt/data.

If you’re talking about configuration, it’s saved in the sqlite file as well.

**Comment by dphildebrandt** [comment]
Never mind, I'm a dummy. For some reason I was thinking that /opt/data had to point to where your media was, rather than obviously connecting through Plex/overseerr/*arrs. Can close this issue.
