### ISSUE TITLE
Support for Ombi

### ISSUE THREAD

**Issue by herkalurk** [jorenn92/Maintainerr#933]
I'd love to see this application have support for reading data from ombi and correlating it to the items in plex and sonarr/radarr.

I have a specific use case where users request movies in ombi, however they don't watch them in plex.  They end up copying from my nas to their own.  It creates a lot of bloat in my movies library.  

The use case and rules I imagine implementing are that I would trigger on movies that a specific user(s) had requested in ombi, matching them to the library item in plex, and then checking to see if anyone had even watched it in plex within 3 -6 months.  Not every movie those users request should be removed, but so often they're the only one that wants them.  I end up doing a manual purge every few months.

I also feel like this could open up other options as ombi is a common tool for multi user support and there are surely other use cases out there with integration of that app.

**Comment by jorenn92** [comment]
There's this (very small) FR for it already. I suggest you +1 that. This way, I'm able to measure how desired some features are.
Feel free to extend the comment with your reasoning. I'm going to close this, to avoid clutter in the issues section.

#910
