### ISSUE TITLE
Cant connect o overserr with a base URL

### ISSUE THREAD

**Issue by Rick45** [jorenn92/Maintainerr#976]
**Describe the bug**
i have overseer in two domains:
[https://overseerr.mydomain.com](https://overseerr.mydomain.com)
[https://mydomain.com/overseerr ](https://mydomain.com/overseerr )

If I configure the first one, it connects without any issue, but when using the second one, it always fails with the connection.

 I can't find a way to connect to it.

**To Reproduce**
1. set the hostname for overseerr in the configuration to something like [https://mydomain.com/overseerr](https://mydomain.com/overseerr )

**Expected behavior**
the connection should be done successfully.

**Comment by Rick45** [comment]
Some extra information, From what i checked the issue is that when the URL has the following format : [https://mydomain.com/overseerr ](https://mydomain.com/overseerr ) the API URL is generated like this:
[https://mydomain.com/overseerr:443/api/v1](https://mydomain.com/overseerr:443/api/v1)

i have hard-coded the ULR to be [https://mydomain.com/overseerr/api/v1](https://mydomain.com/overseerr/api/v1) and works as expected.

**Comment by jorenn92** [comment]
Thanks for you report! This indeed seems to be an oversight.
