### ISSUE TITLE
Rule doesn't work without all apps configured, even apps not used

### ISSUE THREAD

**Issue by yroyathon** [jorenn92/Maintainerr#977]
**Describe the bug**
I've configured Plex/Sonarr/Radarr in the Maintainerr setup.  But I can't setup Overseerr due to issue #976 .  I've created a simple rule, but it will not run and produce results in the collection.  The log contains "[RuleExecutorService] Not all applications are reachable.. Skipped rule execution."  It would be nice if the rules would work even if some of the apps were not configured, apps that are not used in the rule.

**To Reproduce**
Setup all apps except Overseerr.  Try to create and run a rule.  No results should appear in the collection.

**Expected behavior**
Creating a simple rule should produce some results in the collection, but it does not.

**Screenshots**

**Device (please complete the following information):**
OS Ubuntu 22.04

**Additional context**

**Comment by jorenn92** [comment]
Can you update the database record manually for now? It's an sqlite database. You should be able to access it with any sqlite editor and edit the settings table. 

Your other option is to wait for a fix of #976

**Comment by yroyathon** [comment]
In the Maintainerr setup, I have all 3 fields filled out correctly in the Settings >> Overseerr section.  But it doesn't work when I click Test, it says Connection failed Please check and save your settings.
What specifically am I updating in the settings table?  I installed sqlitebrowser.  Oh, perhaps the Overseerr_url that doesn't look quite right, per the bug we mentioned.  I'll give changing it a try...
That seems to have done the trick!  My rule ran and generated results.  Now I actually get to use your app.
FYI the Overseerr Settings now don't display correctly (no overseerrr in the url, blank port), BUT, when I Test it it is successful.  I'm sure future bug fixes will address all of this.
Thanks very much for the workaround.

**Comment by jorenn92** [comment]
> In the Maintainerr setup, I have all 3 fields filled out correctly in the Settings >> Overseerr section. But it doesn't work when I click Test, it says Connection failed Please check and save your settings. What specifically am I updating in the settings table? I installed sqlitebrowser. Oh, perhaps the Overseerr_url that doesn't look quite right, per the bug we mentioned. I'll give changing it a try... That seems to have done the trick! My rule ran and generated results. Now I actually get to use your app. FYI the Overseerr Settings now don't display correctly (no overseerrr in the url, blank port), BUT, when I Test it it is successful. I'm sure future bug fixes will address all of this. Thanks very much for the workaround.

Thank you for confirming the workaround! I'll fix this in a future update.
