### ISSUE TITLE
v2 with compose, fresh install does not allow access to plex, sonarr, radarr configuration options

### ISSUE THREAD

**Issue by sbe-arg** [jorenn92/Maintainerr#991]
options for setting integrations is greyed out and cannot be clicked. 
running on latest v2

**Comment by sbe-arg** [comment]
I cannot configure plex either

**Comment by jorenn92** [comment]
Are you not able to configure the Plex options? Or is the communication with your server failing?

**Comment by sbe-arg** [comment]
I run the compose on the same server as plex and its not detecting the plex server not allowing me to even click on the plex tab

**Comment by jorenn92** [comment]
It's not supposed to auto detect Plex, it should redirect you to the Plex settings screen on first boot. Once you've successfully configured your Plex server, the other options will become available. 

What screen are you on when you open Maintainerr's UI? Can you share screenshots?

**Comment by sebortner** [comment]
I‘m not sure if this is the same topic, but I have a similar problem with a fresh install of Maintainerr. Upon first boot, I do get redirected to the /settings page, but nothing renders.
@
![IMG_0770](https://github.com/jorenn92/Maintainerr/assets/46000815/a900bec6-1248-4fba-9d95-401a5153af38)

**Comment by sbe-arg** [comment]
Exacly this

**Comment by jorenn92** [comment]
Ah yes, you'll have to manually make sure the directory is actually read/writeable by the correct user. 
This is documented, but perhaps i should add a bold font to it:

![image](https://github.com/jorenn92/Maintainerr/assets/9069536/9721a5cf-1744-4e05-ab06-c483071d526d)

**Comment by sebortner** [comment]
Yeah, my bad. I should have created the directory prior to spinning up the container for the first time. But like I mentioned, a simple `chown` fixed that.

**Comment by sbe-arg** [comment]
But even if I start this creating a volume where the opt data is within the volume I get the same error.

Why do we have to mount the data volume?
Is this data volume the media?

Its not clear

**Comment by jorenn92** [comment]
The /opt/data directory contains your database and logs. You can start the application without it, but you’d lose all settings, rules and collections after each reboot.

If it’s still not working, i advise you to double check the permissions again. The app user needs full read/write access to the folder you mounted /opt/data to.

**Comment by sbe-arg** [comment]
Im starting it with a docker volume the permissions should be r/w by default.

**Comment by jorenn92** [comment]
They should, but it doesn’t hurt to check. I suggest you try to exec in the container and create a file inside the /opt/data directory. Does that work? Also, is there a database file and a logs folder?

If that works, please paste your log here, perhaps the reason is in there.
