### ISSUE TITLE
Unraid error with permission

### ISSUE THREAD

**Issue by nierdal** [jorenn92/Maintainerr#992]
Unraid show this error. The container is not configured as privileged : 

spawned: 'server' with pid 101 THE CONTAINER NO LONGER OPERATES WITH PRIVILEGED USER PERMISSIONS. PLEASE UPDATE YOUR CONFIGURATION ACCORDINGLY: https://github.com/jorenn92/Maintainerr/releases/tag/v2.0.0

I added to the extra parameters :   -u 1000:1000

But still have the error. Thanks in advance!

**Comment by jorenn92** [comment]
Unraid requires some extra steps because Ibracorp didn’t update the community app for v2 yet. These steps are specified in this pinned discussion:

https://github.com/jorenn92/Maintainerr/discussions/851

**Comment by ydkmlt84** [comment]
Closing for now but if there is still a problem, please re-open.
