### ISSUE TITLE
Will not connect to Overseer, Radarr, Sonarr

### ISSUE THREAD

**Issue by RooHTaylor** [jorenn92/Maintainerr#993]
Maintainerr installed via Docker, as described in the docs.
Overseer, Radarr, and Sonarr installed on the same machine, and are all listening via plain and SSL ports on the interface IP address.

With the fresh Maintainerr install, no mater what combination of `http(s)://<domain/ip> <port>` I attempted to enter into the Settings pages, Maintainer would not connect to Overseer, Radarr, or Sonarr.  Plex connected right away after authenticating.

OS: Ubuntu 22.04.4
Docker: 24.0.5

The only error message is: 

> Connection failed! Please check and save your settings

Only entry I see in the log file in the data folder is:
`[maintainerr]  |  23/03/2024 00:53:28  [WARN] [RadarrApi] Couldn't fetch Radarr info.. Is Radarr up?`

**Comment by jorenn92** [comment]
I've added PR #996 to this issue, since i believe this is related and might be the same problem. Please create a new issue if the problem persists after this is merged.
