### ISSUE TITLE
Add user notifications similar to Overseerr

### ISSUE THREAD

**Issue by mr1-000** [jorenn92/Maintainerr#994]
**Is your feature request related to a problem? Please describe.**
It can be difficult for non-admin Plex users to know when their requests are close to leaving after being added to a collection by Maintainerr.

**Describe the solution you'd like**
Add user notifications similar to Overseerr. Ideally, it could be set up with rules similar to the main application feature - i.e., notify the Overseerr requester when their request is added to a collection, when it will be removed in X days, etc.

Specifically I would only use Discord notifications, but Overseerr also offers Pushbullet and Pushover notifications.

**Describe alternatives you've considered**
I have considered manually notifying users which is not really feasible with many users. Maintainerr does helpfully put items into collections for users to browse, but it can be difficult to tell what was added recently when there is a large volume of items in the collection.

**Comment by NightHawkATL** [comment]
I second this request as I would like to get notifications on items in collection being added or that a rule has created a collection to allow time to view the collection and make decisions before they are deleted.

**Comment by Dosk3n** [comment]
I just came to request the same thing.

**Comment by jorenn92** [comment]
Hey! Please don't create issues for feature requests, this clutters the issue view. 

There's an open FR for notification support @ https://github.com/jorenn92/Maintainerr/discussions/866. please up this and comment there. I measure desired features based on these feature requests, and ignore FR's requested through an issue.
